CREATE TABLE `investor_inquiries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`status` enum('new','contacted','in_discussion','committed','declined','archived') NOT NULL DEFAULT 'new',
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`organization` varchar(255),
	`role` varchar(255),
	`location` varchar(255),
	`investorType` enum('individual','family_office','foundation','impact_fund','institutional','other') NOT NULL,
	`investmentRange` enum('under_10k','10k_50k','50k_100k','100k_500k','500k_1m','over_1m') NOT NULL,
	`investmentTimeline` enum('immediate','3_months','6_months','1_year','exploring') NOT NULL,
	`primaryInterest` enum('land_projects','alliance_fund','both') NOT NULL,
	`geographicPreference` text,
	`sectorInterests` text,
	`investmentExperience` text,
	`motivations` text,
	`impactGoals` text,
	`questionsForTeam` text,
	`referralSource` varchar(255),
	`documentsUrl` text,
	`additionalNotes` text,
	`preferredContact` enum('email','phone','video_call') NOT NULL DEFAULT 'email',
	`newsletterOptIn` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `investor_inquiries_id` PRIMARY KEY(`id`)
);
