CREATE TABLE `general_inquiries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`status` enum('new','contacted','in_progress','completed','archived') NOT NULL DEFAULT 'new',
	`pathType` enum('land_partner','create_with_regens','alliance','finance','live','role','something_else') NOT NULL,
	`email` varchar(320) NOT NULL,
	`fullName` varchar(255),
	`projectUrl` varchar(512),
	`projectInspiration` text,
	`projectProgress` text,
	`allianceOrganizations` text,
	`otherOrganization` varchar(255),
	`organizationUrl` varchar(512),
	`partnershipDescription` text,
	`landProjects` text,
	`otherProject` varchar(255),
	`roleArchetypes` text,
	`roleInterest` text,
	`uniqueContribution` text,
	`additionalNotes` text,
	`referralSource` varchar(255),
	`newsletterOptIn` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `general_inquiries_id` PRIMARY KEY(`id`)
);
