CREATE TABLE `campaign_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` int NOT NULL,
	`category` enum('land','equipment','role','resource') NOT NULL,
	`hectares` int,
	`region` varchar(255),
	`features` text,
	`videoUrl` varchar(500),
	`landDescription` text,
	`equipmentName` varchar(255),
	`equipmentQuantity` int DEFAULT 1,
	`equipmentCategory` varchar(100),
	`roleTitle` varchar(255),
	`hoursPerWeek` int,
	`durationMonths` int,
	`roleDescription` text,
	`resourceName` varchar(255),
	`resourceQuantity` int DEFAULT 1,
	`resourceUnit` varchar(50),
	`resourceDescription` text,
	`estimatedValue` int NOT NULL DEFAULT 0,
	`pledgedValue` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `campaign_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`status` enum('draft','active','funded','completed','cancelled') NOT NULL DEFAULT 'active',
	`title` varchar(255) NOT NULL,
	`description` text NOT NULL,
	`projectName` varchar(255) NOT NULL,
	`location` varchar(255),
	`financialTarget` int NOT NULL DEFAULT 0,
	`currency` varchar(10) DEFAULT 'USD',
	`totalValue` int NOT NULL DEFAULT 0,
	`landValue` int NOT NULL DEFAULT 0,
	`equipmentValue` int NOT NULL DEFAULT 0,
	`rolesValue` int NOT NULL DEFAULT 0,
	`resourcesValue` int NOT NULL DEFAULT 0,
	`pledgedTotal` int NOT NULL DEFAULT 0,
	`pledgedLand` int NOT NULL DEFAULT 0,
	`pledgedEquipment` int NOT NULL DEFAULT 0,
	`pledgedRoles` int NOT NULL DEFAULT 0,
	`pledgedResources` int NOT NULL DEFAULT 0,
	`pledgedFinancial` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`publishedAt` timestamp,
	`completedAt` timestamp,
	CONSTRAINT `campaigns_id` PRIMARY KEY(`id`)
);
