CREATE TABLE `campaign_contributions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` int NOT NULL,
	`campaignItemId` int,
	`userId` int,
	`contributorName` varchar(255) NOT NULL,
	`contributorEmail` varchar(320) NOT NULL,
	`contributorPhone` varchar(50),
	`contributorBio` text,
	`contributionType` enum('land','equipment','role','resource','financial') NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`landHectares` int,
	`landRegion` varchar(255),
	`landFeatures` text,
	`equipmentName` varchar(255),
	`equipmentQuantity` int,
	`equipmentCondition` varchar(50),
	`roleTitle` varchar(255),
	`hoursPerWeek` int,
	`durationMonths` int,
	`skills` text,
	`resourceName` varchar(255),
	`resourceQuantity` int,
	`resourceUnit` varchar(50),
	`financialAmount` int,
	`financialCurrency` varchar(10) DEFAULT 'USD',
	`paymentMethod` varchar(50),
	`estimatedValue` int NOT NULL DEFAULT 0,
	`status` enum('pending','accepted','rejected','withdrawn','fulfilled') NOT NULL DEFAULT 'pending',
	`contributorNotes` text,
	`ownerNotes` text,
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`reviewedAt` timestamp,
	`fulfilledAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `campaign_contributions_id` PRIMARY KEY(`id`)
);
