CREATE TABLE `letter_of_intent` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`status` enum('pending','confirmed','withdrawn','converted') NOT NULL DEFAULT 'pending',
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`organization` varchar(255),
	`role` varchar(255),
	`pledgeAmount` int NOT NULL,
	`investorType` enum('individual','family_office','foundation','impact_fund','institutional','other') NOT NULL,
	`investmentTimeline` enum('immediate','3_months','6_months','1_year','flexible') NOT NULL DEFAULT 'flexible',
	`geographicPreference` text,
	`sectorInterests` text,
	`motivations` text,
	`questionsForTeam` text,
	`additionalNotes` text,
	`referralSource` varchar(255),
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`confirmedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `letter_of_intent_id` PRIMARY KEY(`id`)
);
