-- SUPERSEDED by 0072_onboarding_quests_category.sql (slug changed to welcome-aboard-quests)
-- Do not run this migration. Run 0072 instead.
-- INSERT INTO forumCategories (slug, name, description, icon, color, sortOrder)
-- VALUES ('onboarding-quests', ...) ON DUPLICATE KEY UPDATE name=name;
