-- Migration 0153: bounty valuation engine
-- Run with: npx tsx scripts/run-migration.ts drizzle/0153_bounty_valuation.sql
--
-- Part 1 of the Bounty Board build. Adds the storage the deterministic
-- valuation engine needs: the full valuation breakdown and the sociocratic
-- overview persisted on each bounty (the overview is already generated by the
-- extract-tasks pass but was discarded), a priorityBoost flag the priority
-- factor reads (never a guess inside computeBountyAmount), and the
-- bounty_demand_factors table the daily flywheel learns into per
-- (circle, scopeTier). See BOUNTY_VALUATION_ENGINE_SPEC.md.

ALTER TABLE bounties
  ADD COLUMN valuationBreakdown JSON NULL,
  ADD COLUMN sociocraticOverviewJson JSON NULL,
  ADD COLUMN priorityBoost TINYINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS bounty_demand_factors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  circle VARCHAR(128) NOT NULL,
  scopeTier ENUM('trivial','small','medium','large') NOT NULL,
  factor DECIMAL(6,4) NOT NULL DEFAULT 1.0000,
  precedentMedian DECIMAL(20,6) NULL,
  sampleSize INT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY bounty_demand_factors_circle_tier (circle, scopeTier)
);
