-- Real titles for harvested ideas.
--
-- The vault sends `title` as the first ~45 characters of the raw note, hard cut
-- mid-word. Of 543 ripe ideas, zero end in punctuation, 409 are 40 to 50
-- characters, and 541 have substantially more summary than title. The feed and
-- the "what would this draw from" panel both read that field, so both looked
-- like broken garbage.
--
-- display_title is generated from the summary and is what the UI shows. `title`
-- stays exactly as the bridge upserts it, so re-syncing from the vault never
-- clobbers a generated title and the whole thing stays reversible: drop this
-- column and the old behaviour returns.
--
-- Generated by server/lib/harvest-titles.ts on the cheap tier, batched, and
-- topped up hourly by runGeneration. Backfill with
-- npx tsx scripts/backfill-idea-titles.ts

ALTER TABLE harvest_ideas
  ADD COLUMN display_title VARCHAR(300) NULL;
