// GENERATED FILE. Edit QUEST_MASTER_SHEET.md instead, then run:
//   pnpm sync:quest-content
// Do not edit this file by hand.

export interface QuestMasterContent {
  id: number | string;
  subtitle: string;
  timeEstimate: string;
  videoUrl?: string;
  pdfUrl?: string;
  storyCard: string[];
  storyTeaser: string[];
  howToSteps: { heading: string; body: string }[];
  deliverable: string;
  tips: string[];
  resources: { label: string; url: string }[];
  connections: {
    comesBefore?: number[];
    referencedBy?: string[];
  };
}

export const QUEST_MASTER_CONTENT: Record<number | string, QuestMasterContent> = {
  0: {
    id: 0,
    subtitle: 'Letting Burn What No Longer Serves',
    timeEstimate: '2 to 4 hours',
    videoUrl: 'https://www.youtube.com/watch?v=U5ZTTy0SCaA',
    storyCard: [
      'We start with the fire.',
      'Fire is an element that can transmute toxicity immediately. A log that has sat for centuries becomes light and warmth and ash in minutes. Stories that have shaped our entire identity can be released in a single ceremony if we are willing.',
      'We live in a time when it is getting harder and harder to know what is real. More effective and more personalized marketing and propaganda means the logical mind alone cannot keep up. We cannot reason our way out of illusions that were designed specifically to bypass reason.',
      'This is why we start here. Not with a plan, not with a strategy, but with a fire. A willingness to look at what we have inherited, what we have built, what we believe about ourselves and the world, and to ask honestly: does this still serve us?',
      'Who are you? Like the rest of us. Nobody. And like the rest of us, a God, a whole person on a path to remembering that wholeness. The fire is where that remembering begins.',
      'When you share your fire with this community you are not just telling us what you believe. You are beginning the initiatory journey. The fire you share here will be referenced again and again as you move through the quests. It is your starting point, your baseline, the you before the game began.',
    ],
    storyTeaser: [
      'We start with the fire.',
      'Fire is an element that can transmute toxicity immediately. A log that has sat for centuries becomes light and warmth and ash in minutes. Stories that have shaped our entire identity can be released in a single ceremony if we are willing.',
    ],
    howToSteps: [
      { heading: 'Step 1: Sit with fire.', body: 'Literally if you can. A candle works. A firepit is better. If you have access to an open fire, spend at least 20 to 30 minutes just watching it. Let your mind wander. Do not try to think productively. Just be with the fire. If you can\'t possibly make a fire, the fire quest video will serve.' },
      { heading: 'Step 2: Journal without editing.', body: 'Write for at least 20 minutes without stopping. Answer these questions in any order, skip any that feel stuck, come back to others that feel alive: What are you carrying that you know is no longer yours? What stories about yourself or the world have you inherited that you are not sure you chose? What would you burn if you could? What has already burned that you are still holding onto? What lights you up? What do you want to contribute before you die?' },
      { heading: 'Step 3: Identify what to release.', body: 'From what you wrote, identify one to three things you are genuinely ready to release. A belief. A story. A pattern. A role. Write each one on a piece of paper.' },
      { heading: 'Step 4: Burn it.', body: 'Safely and with intention. You can do this alone or with others. Speak each thing aloud as you offer it to the fire. Take your time.' },
      { heading: 'Step 5: Write your fire.', body: 'After the burning, write freely about what you are moving toward. What you want to build. What lights you up. What you would do if the old story were truly gone. This becomes your quest artifact.' },
      { heading: 'Step 6: Create and share.', body: 'Turn your fire story into a video (3 minutes or less), a written piece, or a voice recording. Share it with the community. Then submit it in the Game Space to claim your tokens.' },
    ],
    deliverable: 'A video, article, or voice recording sharing your fire and what you released.',
    tips: [
      'Be real. The community can tell the difference between a genuine fire and a performance. Nobody needs a performance.',
      'If you find it hard to name what to release, start with something small. The fire takes what you give it.',
      'You can return to this quest. Burning is not a one-time act. Many players do a fire ceremony each season.',
    ],
    resources: [
      { label: 'Watch intro video', url: 'https://www.youtube.com/watch?v=U5ZTTy0SCaA' },
      { label: 'SEEDS Quest Guide', url: 'https://explore.joinseeds.earth/regen-civics-infinite-game/play-the-game/quest' },
    ],
    connections: {
      comesBefore: [1],
      referencedBy: [
        'Referenced by: All seasonal quests that involve letting go or transition (Air season)',
      ],
    },
  },
  1: {
    id: 1,
    subtitle: 'Healing Modalities',
    timeEstimate: '3 to 5 hours',
    videoUrl: 'https://www.youtube.com/watch?v=pbhGgg2GZUM',
    storyCard: [
      'Your gut is not just a digestive organ. It has its own nervous system, around 100 million neurons, more than your spinal cord. Scientists now call it the enteric nervous system, and many refer to it as the second brain. Your heart has a similar network, 40,000 neurons of its own, processing information independently before it ever reaches your head.',
      'Three minds. All of them influenced by what you eat, drink, and ferment.',
      'When we add living microbiology to our bodies, we are literally changing the information processing happening in all three of those minds. The research on the gut-brain axis is some of the most exciting biology of the last 20 years. The microbes in your gut communicate directly with your brain via the vagus nerve. They influence mood, cognition, inflammation, and immune function. Different populations of microbes correspond to different emotional and cognitive states.',
      'This is why the Potions quest comes before the planting quests. You are not just making fermented drinks and herbal preparations because they taste good or because they are "healthy." You are building an ecosystem inside yourself. An ecosystem that will then shape how you think, feel, and perceive. An ecosystem that will travel with you into the forest when you plant seeds, enriching the soil with the expanded diversity of your own body.',
      'The potion you make is both medicine and initiation.',
    ],
    storyTeaser: [
      'Your gut is not just a digestive organ. It has its own nervous system, around 100 million neurons, more than your spinal cord. Scientists now call it the enteric nervous system, and many refer to it as the second brain. Your heart has a similar network, 40,000 neurons of its own, processing information independently before it ever reaches your head.',
      'Three minds. All of them influenced by what you eat, drink, and ferment.',
    ],
    howToSteps: [
      { heading: 'Step 1: Watch the video.', body: 'The tutorial video walks you through making a potion. Follow along before you start experimenting on your own.' },
      { heading: 'Step 2: Choose your potions.', body: 'Select 1 to 3 healing herbs to add to your preparation that you want to make and showcase. Work with what is available in your bioregion.' },
      { heading: 'Step 3: Gather your ingredients.', body: 'Source all ingredients locally where possible. Farmers markets, foraged (only what you can identify with certainty), or your own garden. The closer to your bioregion, the more relevant the microbiology will be to your body and your land.' },
      { heading: 'Step 4: Make your potions.', body: 'Document the process as you go. Photos, short video clips, notes. What did you make? What went into it? What is the tradition or logic behind this preparation?' },
      { heading: 'Step 5: Taste, feel, notice.', body: 'After taking your potion, sit with it. What do you notice? Any immediate effects? How does your gut feel? Your mood? Your energy? Note this down. Continue reflecting over the next days and weeks as this ancient and diverse biology mixes with yours.' },
      { heading: 'Step 6: Share your showcase.', body: 'Create a short video or article showing your potions, how you made them, what you noticed, and what you would recommend to others. Post it on your socials and add the link to your game space proposal.' },
    ],
    deliverable: 'A "Showcasing My Potions" video or article, posted publicly and submitted in the Game Space.',
    tips: [
      'You do not have to be an expert herbalist or fermentation nerd. Beginners make the most honest and useful content because they share what actually confused them and how they figured it out.',
      'The three minds framework (gut, heart, head) is worth reading about before you start. Explore polyvagal theory, the gut-brain axis, and HeartMath research.',
      'If you make fermented foods regularly over time, the effect compounds. One batch is a taste; a month of daily fermented foods is a transformation.',
      'Wild ferments use wild yeast and bacteria from your local environment to connect you directly to your bioregion\'s microbiology.',
    ],
    resources: [
      { label: 'Watch Potions Tutorial Video', url: 'https://www.youtube.com/watch?v=pbhGgg2GZUM' },
      { label: 'HeartMath Institute', url: 'https://www.heartmath.org' },
      { label: 'The Second Brain by Michael Gershon (book)', url: '' },
    ],
    connections: {
      comesBefore: [0],
      referencedBy: [
        'Unlocks: Quest 4 (Food Foresting) at full potency. Your saliva now carries a richer ecosystem',
      ],
    },
  },
  2: {
    id: 2,
    subtitle: 'Saving Abundance',
    timeEstimate: '1 to 2 hours (ongoing practice)',
    storyCard: [
      'Seeds are the oldest technology humans have ever stewarded. For most of human history, the selection, saving, trading, and planting of seeds was a central act of community life. Villages and bioregions developed distinct seed libraries over hundreds of generations, adapted to specific climates, soils, and tastes. That diversity is more than agricultural wealth. It\'s a cultural memory that co-evolved with the beings who stewarded it.',
      'In the last century, the industrialization of food production collapsed that diversity dramatically. Varieties that fed communities for generations disappeared from cultivation. The seeds that remained were increasingly owned, patented, and controlled by corporations whose interest in them had more to do with profit than with feeding people or healing land.',
      'Seed saving is an act of resistance and of love. When you save a seed, you are making yourself a link in a chain that stretches back thousands of years. When you swap a seed with someone else, you are weaving that chain across bioregions and cultures.',
      'The LocalScale platform is our game\'s infrastructure for seed swapping. By listing your seeds there you become part of a living network of people who are rebuilding food sovereignty one variety at a time.',
    ],
    storyTeaser: [
      'Seeds are the oldest technology humans have ever stewarded. For most of human history, the selection, saving, trading, and planting of seeds was a central act of community life. Villages and bioregions developed distinct seed libraries over hundreds of generations, adapted to specific climates, soils, and tastes. That diversity is more than agricultural wealth. It\'s a cultural memory that co-evolved with the beings who stewarded it.',
    ],
    howToSteps: [
      { heading: 'Step 1: Gather your seeds.', body: 'Collect seeds from plants you have grown, received, purchased, or foraged. Focus on heirloom and open-pollinated varieties (not hybrids, which do not breed true). Good candidates: tomatoes, peppers, beans, squash, cucumbers, herbs, flowers, fruit trees.' },
      { heading: 'Step 2: Clean and dry your seeds.', body: 'Remove pulp or chaff. Dry thoroughly before storing. Seeds with any moisture will mold. Spread them on a paper towel in a warm, dry place for a week.' },
      { heading: 'Step 3: Label and document.', body: 'For each variety, note: name (common and Latin if you know it), source, year saved, growing zone, any growing tips or stories about this variety. The story matters as much as the data.' },
      { heading: 'Step 4: Set up your LocalScale profile.', body: 'Create or update your profile at localscale.org.' },
      { heading: 'Step 5: List your seeds for swap.', body: 'Add each variety with clear descriptions, photos if you have them, and what you would like in return (other seeds, skills, nothing at all).' },
      { heading: 'Step 6: Connect and trade.', body: 'Reach out to others in your area or bioregion. Arrange swaps. Meet in person if you can.' },
    ],
    deliverable: 'Active seed listings on your LocalScale profile. Share the link as your quest submission.',
    tips: [
      'If you are just starting, even one or two varieties listed is a valid submission. The point is to begin.',
      'Include growing zone and any unusual requirements (shade tolerant, drought tolerant, etc.) so swappers know what they are getting.',
      'The best seeds to save first are the ones you actually grow and love eating. Start there.',
      'Seed swaps are often social events. If you know other gardeners in your area, propose a swap gathering.',
    ],
    resources: [
      { label: 'LocalScale Platform', url: 'https://localscale.org' },
      { label: 'Seed Savers Exchange (seedsavers.org) for variety documentation inspiration', url: '' },
    ],
    connections: {
      comesBefore: [1],
      referencedBy: [
        'Feeds into: Quest 4 (Food Foresting). The seeds you save get planted',
      ],
    },
  },
  3: {
    id: 3,
    subtitle: 'Loving Earth, Healing Ourselves',
    timeEstimate: '3 to 5 hours (ongoing practice)',
    storyCard: [
      'The soil is not separate from you. Healthy living soil contains billions of microorganisms per teaspoon, a greater diversity of life than almost any other ecosystem on Earth (besides our own healthy guts!). Those organisms are in constant communication with plant roots, with fungi, and through the food we eat, with us. When you put your hands in healthy soil, you are touching a living mind.',
      'Indigenous cultures understood this. The belief that our health and the health of our land are the same thing was not mysticism. It was ecology, and now science is catching up to this reality.',
      'This quest is about creating a healing space in the Earth. Not a clean, managed garden bed in a raised planter. A healing hole. A place where the life cycles of your family pass back into the ground. Where fungi connect trees and plants in underground networks. Where the oldest trees in your bioregion share their seed genetics with new life. Where the soil grows more alive year by year.',
      'It is also an invitation to change your relationship with what our culture calls waste.',
      'Long ago our ancestors went through a transition that made our relationship to nature profane. Today that looks like the widespread belief that our own waste is purely toxic, something to be flushed away and forgotten. But our humanure (feces), composted correctly, is one of the most potent soil amendments on Earth. Our bodies are part of the cycle. When we remove ourselves from that cycle, we impoverish both ourselves and the land.',
      'This quest asks you to step back into the cycle.',
    ],
    storyTeaser: [
      'The soil is not separate from you. Healthy living soil contains billions of microorganisms per teaspoon, a greater diversity of life than almost any other ecosystem on Earth (besides our own healthy guts!). Those organisms are in constant communication with plant roots, with fungi, and through the food we eat, with us. When you put your hands in healthy soil, you are touching a living mind.',
    ],
    howToSteps: [
      { heading: 'Step 1: Find your space.', body: 'Identify a patch of ground you have access to and care for. This could be a backyard, a community garden plot, a strip of neglected land near your home. It does not need to be large.' },
      { heading: 'Step 2: Gather fungi.', body: 'If you can access an old-growth forest or the oldest forest in your bioregion, collect a small amount of soil and leaf litter from the base of large, healthy trees. This material contains local mycorrhizal fungi. You are going to introduce them to your healing space.' },
      { heading: 'Step 3: Collect seeds from old trees.', body: 'Gather seeds or cuttings from the oldest, healthiest plants and trees in your local area. These genetics carry the deepest adaptation to your specific place along with seeds of fruiting plants, nitrogen fixers and as many of the 7 layers of the forest as you can.' },
      { heading: 'Step 4: Dig your first healing hole.', body: 'About 1\' deep, 3-4\' wide. This is where your material will go.' },
      { heading: 'Step 5: Feed the hole.', body: 'Add a layer of your family\'s composted organic matter (humanure if you are practicing that, some saliva if not), a layer of the forest floor material you collected (to introduce fungi), and your seeds. Cover with soil. Plant out a diversity of food plants around the site if possible. Then mulch the ground after you water it to protect the bare soil from direct sunlight - but not too deep as to suffocate the seeds.' },
      { heading: 'Step 6: Tend it.', body: 'Return weekly. Notice what grows. Add more material when you dig the next hole nearby. The practice is ongoing: 1 hole per week as your compost bucket fills up, each seeded with a diversity of food plants, slowly building a food forest on your domain from the ground up. Each "whole" will heal outwards and year after year expanding itself and healing the grounds around it.' },
      { heading: 'Step 7: Document and share.', body: 'Create a short video or article showing your healing space, what you did, what you are learning. Include what surprised you.' },
    ],
    deliverable: 'A "Showcasing My Healing Whole" video or article documenting your practice.',
    tips: [
      'This is a long-term practice, not a one-time event. Your submission can document the beginning of the practice.',
      'If you cannot compost humanure yet, a worm bin or regular compost bin is a valid starting point. The practice evolves. You can use your saliva to add your DNA and biology to the whole.',
      'The fungi introduction from old forest soil is powerful but optional for your first submission. Focus on getting the holes dug and seeded.',
      'Building comfy walking paths (wood chips, straw, old logs) through your healing space makes it more likely you will spend time there.',
    ],
    resources: [
      { label: 'Humanure Handbook by Joseph Jenkins (free online)', url: '' },
      { label: 'Fungi Perfecti', url: 'https://fungi.com' },
      { label: '"Wood Wide Web" research on mycorrhizal networks (search: Suzanne Simard forest communication)', url: '' },
    ],
    connections: {
      comesBefore: [2],
      referencedBy: [
        'Pairs with: Quest 4 (Food Foresting). Same practice, different scale (your domain vs. public land)',
      ],
    },
  },
  4: {
    id: 4,
    subtitle: 'Being Human Again',
    timeEstimate: '2 to 4 hours (repeatable infinitely)',
    storyCard: [
      'Our forests used to be full of food.',
      'Before industrialization, before timber plantations, before the great clearing, the forests of most temperate regions were not just "wild spaces" as we\'re told. They were tended landscapes, full of fruit trees, nut trees, berry bushes, root vegetables, and herbs. The people who lived in and around them participated in their abundance.',
      'Then we cut them down.',
      'We replanted some of them with timber monocultures. Lines of identical trees, all the same age, no understory, no diversity, nothing for most animals to eat. Some call these forests. Many ecologists do not.',
      'The places we now call forests are often just timber plantations: uniform, quiet, largely lifeless compared to what they replaced.',
      'The Food Foresting quest is about changing that. One seed at a time. One walk at a time.',
      'Here is the math: if you planted just one seed every ten minutes on a one-hour walk, that is six seeds. Do that walk once a month for a year and you have planted 72 potential trees. Each mature fruit tree can produce hundreds to thousands of seeds annually. The animals and future humans who enjoy your trees will spread those seeds further. A single tree planted today can generate millions more during a human lifetime.',
      'We get to say that forests of the future will be diverse food forests again because by simply planting seeds we are playing a game that creates that future. Every seed is a move.',
    ],
    storyTeaser: [
      'Our forests used to be full of food.',
      'Before industrialization, before timber plantations, before the great clearing, the forests of most temperate regions were not just "wild spaces" as we\'re told. They were tended landscapes, full of fruit trees, nut trees, berry bushes, root vegetables, and herbs. The people who lived in and around them participated in their abundance.',
      'Then we cut them down.',
    ],
    howToSteps: [
      { heading: 'Step 2: Prepare your seeds.', body: 'Hold the seeds in your mouth for several minutes before planting. Your saliva adds your DNA, your microbiology, and your bioregion\'s ecosystem to the seed\'s surface. After the Potions quest, this is even more powerful because the diversity of life in your mouth is richer. This is not folklore. Plants inoculated with diverse microbiology establish faster and are more resilient.' },
      { heading: 'Step 3: Scout your location.', body: 'Walk in public parks, forests, or green spaces. Look for places where a fruit tree could thrive without being mowed or disturbed. Forest edges, sunny gaps in the canopy, stream banks, and open slopes are all good candidates. Ideal homes for new seeds are places that will stay moist (beside recently dead tree stumps) that will get partial sunlight and where the tree can grow into getting more sunlight - also somewhere that doesn\'t get mowed/regularly cut down.' },
      { heading: 'Step 4: Plant with intention.', body: 'While you\'re looking for an ideal home for them, send the seeds your intentions and thoughts, maybe imagine how the tree will grow up to feed so many humans and animals. When you find a place - push the seed into the soil with your finger or a small stick. A few centimeters deep (the general rule is to plant as deep as the seed is big). Cover it. If the soil is very dry, water a little. Plant multiple seeds in each location to increase the odds.' },
      { heading: 'Step 5: Mark your spots.', body: 'Note locations so you can return and see if they sprouted. A photo with GPS, a note in your phone, a mark on a map.' },
      { heading: 'Step 6: Bring friends.', body: 'The more the merrier. Make it a celebration. Bring the fruit for everyone to eat together. Make it a ritual. The author of this Quest does this regularly with his young son.' },
      { heading: 'Step 7: Document and share.', body: 'A short video or article of your adventure. What you planted, where, what it felt like. Submit in the Game Space.' },
    ],
    deliverable: 'A video (under 3 minutes) and/or written article about your food foresting adventure.',
    tips: [
      'This quest can be done again and again. Each time counts.',
      'Choose species that will thrive without maintenance once established. Natives and naturalized species are best. Research what fruit trees are native or well-adapted to your bioregion.',
      'Apples, pears, plums, cherries, figs, mulberries, persimmons, and pawpaws are good starting points for temperate climates.',
      'Make it a celebration. Bring snacks, music, and joy.',
    ],
    resources: [
      { label: 'Agroforestry Research Trust', url: 'https://www.agroforestry.co.uk' },
      { label: 'Plants For A Future (pfaf.org) (edible, medicinal, and useful plants by region)', url: '' },
    ],
    connections: {
      comesBefore: [1, 2],
      referencedBy: [
        'Repeatable: Every time you do this quest it earns tokens. There is no limit.',
      ],
    },
  },
  5: {
    id: 5,
    subtitle: '',
    timeEstimate: '3 to 6 hours (ongoing practice)',
    storyCard: [
      'Most of us have spent so little time in spaces that were designed for us to actually rest, connect, and feel held. Not productivity spaces. Not entertainment spaces. Spaces that invite the body to exhale.',
      'We have inherited an architecture of efficiency. Offices, rental apartments, generic furniture, overhead lighting, no nature, no quiet. And we have inherited relational architectures to match: transactional, guarded, optimized. The result is that many of us go through entire seasons of life without ever fully arriving somewhere.',
      'This quest is an invitation to dream and build differently, starting with where you already are.',
      'A space of love is not expensive or elaborate. It is intentional. It holds the needs of the people inside it: warmth, beauty, places to sit together, some living thing growing nearby, enough quiet to actually hear each other. It might be a corner of a room, a backyard, a community gathering space, a forest glade you tend. It is somewhere that when you enter it, your shoulders drop.',
      'When you build a space like this and share it, you give others permission to want the same.',
    ],
    storyTeaser: [
      'Most of us have spent so little time in spaces that were designed for us to actually rest, connect, and feel held. Not productivity spaces. Not entertainment spaces. Spaces that invite the body to exhale.',
    ],
    howToSteps: [
      { heading: 'Step 1: Reflect on what rest and love actually require.', body: 'Before you build anything, sit with these questions: Where do you feel most at home in the world? What does that place have that others lack? What would it take to feel that way in your daily environment? Write your answers down.' },
      { heading: 'Step 2: Choose a space to work with.', body: 'Pick somewhere you have access to and some ability to shape. Your home, a community space, an outdoor area, a corner of a shared workspace. Start where you have permission and influence.' },
      { heading: 'Step 3: Identify what the space currently lacks.', body: 'Walk through it slowly. Notice the light, the air, the surfaces, the sounds, the smells. What does it invite you to do? What does it make impossible? What would need to change for this to be a space people genuinely want to gather in?' },
      { heading: 'Step 4: Dream it into something different.', body: 'Sketch, write, or vision-board what this space could be. You do not need a budget. Start with what is already there and what can be moved, planted, found, or made. Bring in natural materials. Living plants. Comfortable seating arranged for conversation, not for screens. A source of warmth or soft light.' },
      { heading: 'Step 5: Do at least one physical act of transformation.', body: 'Rearrange, plant, build, or clear something. Document the before and after.' },
      { heading: 'Step 6: Use the space with others.', body: 'Gather someone you care about in this space. Share a meal, a conversation, or simply time. Notice how the space affects what becomes possible between you.' },
      { heading: 'Step 7: Document and share.', body: 'Create a short piece (video, photos with reflection, or written) showing your space and what you learned from building and using it.' },
    ],
    deliverable: 'A documented space transformation with reflection on what changed in how people related inside it.',
    tips: [
      'The single biggest change in most indoor spaces is adding living plants and removing overhead fluorescent light. Start there.',
      'A space that invites connection faces seats toward each other, not toward a screen.',
      'Outdoor spaces count. A fire circle, a garden corner with seating, a hammock grove. The Earth is the most healing space material there is.',
      'Include something for the senses beyond sight: a scent, a texture, the sound of water or wind.',
    ],
    resources: [
      { label: 'The Timeless Way of Building by Christopher Alexander (on spaces that feel alive)', url: '' },
      { label: 'Your Homes, Your Choices (explore pattern language for human-scale spaces)', url: '' },
    ],
    connections: {
      referencedBy: [
        'Comes after: Quests 0-4 (personal vitality). You need energy and presence to tend a space',
        'Leads toward: Quest 7 (Healing Circles). The space you create becomes the container for the circle',
      ],
    },
  },
  6: {
    id: 6,
    subtitle: '',
    timeEstimate: '2 to 4 hours (ongoing practice)',
    storyCard: [
      'Love needs tending. Not just feeling, but practice.',
      'Most of us were never taught the practices that sustain love across years and decades. We were given the feeling, or the idea of it, but not the rites. So when love cools or gets complicated, we do not have a structure to return to. We just improvise, or we stop trying.',
      'Rites are different from routines. A routine is something you do on autopilot. A rite is something you do with attention, marking it as significant. When you light a candle for a shared meal, when you speak what you are grateful for before sleeping, when you build a fire together at the change of a season, when you sit with someone after a rupture and say: I am still here, I want to repair this, when you find your way back to each other. These are rites. They create a rhythm that love can anchor to.',
      'Every healthy culture has had rites of love. Courtship rituals. Seasonal celebrations that brought communities together. Ways of marking birth, partnership, and death with the people closest to us. Most of those structures have dissolved in modern life, and we have not replaced them with anything. This quest is an invitation to build some.',
      'You do not need to inherit a tradition. You can design rites that are true to your actual life and relationships.',
    ],
    storyTeaser: [
      'Love needs tending. Not just feeling, but practice.',
      'Most of us were never taught the practices that sustain love across years and decades. We were given the feeling, or the idea of it, but not the rites. So when love cools or gets complicated, we do not have a structure to return to. We just improvise, or we stop trying.',
    ],
    howToSteps: [
      { heading: 'Step 1: Map the love relationships in your life.', body: 'Partner, friends, family, community, relationship to a place. Choose one or two to focus on for this quest.' },
      { heading: 'Step 2: Identify where rites are already present.', body: 'Even informally. A morning exchange. An annual gathering. A way of greeting. Note what already exists and what it does for the relationship.' },
      { heading: 'Step 3: Identify where rites are absent but needed.', body: 'Where does your relationship lack structure for the difficult moments? For celebration? For repair? Where have you wished there was a way to mark something but did not have one?' },
      { heading: 'Step 4: Design at least one new rite.', body: 'Keep it simple and honest to who you are. A rite you will not actually do is worse than none. Design one that fits your life: a weekly check-in format, a seasonal celebration, a repair practice for after conflict, a way of marking gratitude.' },
      { heading: 'Step 5: Practice it.', body: 'Do it at least three times before submitting your quest. Note how it changes the relationship.' },
      { heading: 'Step 6: Reflect and share.', body: 'Write or record a reflection on what you built, what it felt like to practice it, and what it opened up. Include something about why you chose this particular rite for this particular relationship.' },
    ],
    deliverable: 'A written or recorded reflection on the rite you designed, practiced, and what it changed.',
    tips: [
      'The simplest rites are often the most durable. A weekly 20-minute walk with a friend is a rite. A morning gratitude exchange is a rite. Start there.',
      'Repair is the most important rite. Every relationship breaks at some point. Having an agreed-upon way to come back to each other is worth more than any celebration ritual.',
      'Rites of place are often overlooked. Visiting a piece of land seasonally, tending a tree, returning to a river annually. Our relationship to place is also a form of love that benefits from rites.',
    ],
    resources: [
      { label: 'The Five Love Languages by Gary Chapman (useful framework for understanding what each person actually needs)', url: '' },
      { label: 'Braiding Sweetgrass by Robin Wall Kimmerer (rites of love with the land)', url: '' },
    ],
    connections: {
      comesBefore: [5],
      referencedBy: [
        'Feeds into: Quest 7 (Healing Circles). Healing circles are themselves a rite of love within community',
      ],
    },
  },
  7: {
    id: 7,
    subtitle: '',
    timeEstimate: '4 to 8 hours (requires gathering others)',
    storyCard: [
      'Most of what passes for support in our culture is advice. Someone shares something painful and the person listening immediately starts solving it. The result is that the person sharing feels even more alone, because what they needed was not a solution. They needed to be witnessed.',
      'A healing circle is a different technology. It is a structured way for people to come together and witness each other honestly, without advice, without fixing, without one-upping, without performing. Just honest presence with whatever is actually happening for each person.',
      'The circle format is ancient. Indigenous cultures around the world used circles for governance, healing, celebration, and grief. The form survived because it works. When everyone can see everyone else, hierarchy dissolves. When there is a structure that holds the space, people can relax into honesty. When the norm is witnessing rather than fixing, people can say what they actually mean.',
      'Most of us have never been in a genuinely held circle. We have been in groups, meetings, sessions. A held circle feels different from the first moment. The quality of attention is different. The depth of what people are willing to say is different. And what happens after, in how the people relate to each other, is different.',
      'Running this quest means building the capacity to hold that space, and then actually using it.',
    ],
    storyTeaser: [
      'Most of what passes for support in our culture is advice. Someone shares something painful and the person listening immediately starts solving it. The result is that the person sharing feels even more alone, because what they needed was not a solution. They needed to be witnessed.',
    ],
    howToSteps: [
      { heading: 'Step 1: Study the basics of circle-holding.', body: 'Read at least one resource on facilitation or circle practice (see Resources below). Understand the difference between advising and witnessing, between fixing and holding.' },
      { heading: 'Step 2: Design your circle.', body: 'Choose: Who will you gather? What is the container? (A shared meal, an outdoor fire, a home gathering, a scheduled call.) What is the opening to settle people in? What is the talking object or turn-taking structure? What is the closing?' },
      { heading: 'Step 3: Set agreements with the group before you start.', body: 'The minimum agreements for a healing circle: confidentiality (what is shared here stays here), no advice unless asked, speak from your own experience (use "I"), listen to understand rather than to respond. Read these aloud at the opening.' },
      { heading: 'Step 4: Hold the circle.', body: 'Let each person speak without interruption. After each person shares, pause before moving on. Invite the group to simply be with what was shared before the next person begins. You do not need to fill the silence. The silence is part of the work.' },
      { heading: 'Step 5: Close with intention.', body: 'End the circle with a brief closing round: one word or one sentence from each person about what they are leaving with.' },
      { heading: 'Step 6: Reflect and share.', body: 'After the circle, write or record a reflection on how it went. What worked? What did you learn about holding space? What shifted in the group?' },
    ],
    deliverable: 'Documentation of a healing circle you held: the structure you used, what happened, and your reflection as the holder.',
    tips: [
      'Your first circle will not be perfect. Hold it anyway. The practice is in the doing, not in the preparation.',
      'The most common mistake is talking too much as the facilitator. Your job is to hold the container, not to fill it.',
      'If people start giving advice or problem-solving, gently redirect: "Let\'s just be with what Maria shared for a moment before we move on."',
      'Circles work best with 4 to 12 people. Smaller than 4 loses the group field. Larger than 12 becomes hard to hold genuine presence for everyone.',
      'Outdoor circles around fire are particularly powerful. The fire holds attention in a way that no meeting room can.',
    ],
    resources: [
      { label: 'The Way of Council by Jack Zimmerman and Virginia Coyle (the foundational text on circle practice)', url: '' },
      { label: 'Nonviolent Communication by Marshall Rosenberg (for understanding the witnessing posture)', url: '' },
      { label: 'Joanna Macy\'s Work That Reconnects (for ecological grief and healing circles)', url: '' },
    ],
    connections: {
      comesBefore: [6],
      referencedBy: [
        'Feeds into: Quest 10 (NVC). The communication practices of NVC deepen what becomes possible in circles',
        'Qualifier for: Community stewardship in many land projects',
      ],
    },
  },
  8: {
    id: 8,
    subtitle: '',
    timeEstimate: '3 to 6 hours (field time + documentation)',
    storyCard: [
      'For most of human history, people knew the land around them intimately. They knew which plants healed and which ones harmed, which fungi fruited after rain, which berries ripened in which week of autumn. That knowledge was not stored in books. It lived in people, passed through hands and seasons and walking together.',
      'In a generation or two, most of that knowledge was lost. Not destroyed, exactly. Just untransmitted. The supermarket made it unnecessary, or so it seemed. And so most people alive today cannot identify ten edible plants within a kilometer of their home, let alone fifty.',
      'Wild foods carry things that cultivated foods do not. Biodiversity in the microbiome they arrive with. Compounds that plants produce when they grow in real competition with other plants, in real soil, in real weather. A nutrient density shaped by actual ecological pressure rather than commercial selection for uniformity and shelf life.',
      'Beyond the nutrition, foraging changes your relationship to a place. When you learn what grows where, you start to see the land differently. It is no longer scenery. It is a conversation. The fruiting of a certain mushroom tells you something about the health of the mycelial network. The presence of certain weeds tells you about the soil history. You become a reader of the land rather than a passenger in it.',
      'Reciprocal harvest means you take only what is offered in abundance, you leave enough to seed and reproduce, and in some cases you tend: clearing around a plant, transplanting, scattering seeds. You are not just a consumer. You are a participant in the ecosystem.',
    ],
    storyTeaser: [
      'For most of human history, people knew the land around them intimately. They knew which plants healed and which ones harmed, which fungi fruited after rain, which berries ripened in which week of autumn. That knowledge was not stored in books. It lived in people, passed through hands and seasons and walking together.',
    ],
    howToSteps: [
      { heading: 'Step 1: Learn your bioregion\'s wild edible landscape.', body: 'Start with 5 to 10 plants or fungi you can identify with certainty in your area. Use local field guides rather than generic ones. Join a local foraging walk or club if one exists. Certainty matters. Do not eat anything you cannot identify with confidence.' },
      { heading: 'Step 2: Go out at least three times over at least two weeks.', body: 'Foraging as a single experience gives you little. Going out across different weather and terrain begins to give you a sense of patterns.' },
      { heading: 'Step 3: Harvest with intention.', body: 'Take no more than a third of any plant in a given area. Leave the rest to seed, recover, and feed others. Where possible, give something back: scatter seeds, clear competitors, water.' },
      { heading: 'Step 4: Prepare and eat what you have found.', body: 'Cook or use your harvest in some way. Note the difference in taste, texture, and how your body responds compared to store-bought equivalents.' },
      { heading: 'Step 5: Document your finds.', body: 'Photos of each species in situ. Notes on where, when, what condition, what you did with it. Build a personal field record.' },
      { heading: 'Step 6: Share your harvest and your knowledge.', body: 'Cook for others using what you found. Share your field record. Teach someone one thing you learned.' },
    ],
    deliverable: 'A field record (photos + notes) of your foraging sessions and a reflection on what changed in your relationship to the land around you.',
    tips: [
      'The three non-negotiables of safe foraging: a local field guide, local expertise (a class, a walk, or a mentor), and the rule that you eat only what you can identify with full certainty. One wrong mushroom can kill you. Take this seriously and it is safe. Ignore it and it is not.',
      'Start with the most distinctive and unambiguous plants in your region. Blackberries, elderberries, nettles, and dandelions are good starting points in most temperate regions because they are easy to identify and abundant.',
      'Fall is the best season for fungi in most temperate climates. Spring is best for many greens. Plan your outings to match what is actually fruiting.',
    ],
    resources: [
      { label: 'A local field guide for your region (look for guides specific to your country or bioregion, not generic worldwide guides)', url: '' },
      { label: 'iNaturalist app (for species identification and community verification)', url: '' },
      { label: 'Forage London, Forage SF, or equivalent local foraging community in your city', url: '' },
    ],
    connections: {
      comesBefore: [2],
      referencedBy: [
        'Pairs with: Quest 3 (Healing Whole). The wild plants and fungi you find can inoculate your healing holes',
        'Feeds into: Quest 9b (Tree Talk). Foraging teaches you to read the land; tree talk deepens the relationship',
      ],
    },
  },
  9: {
    id: 9,
    subtitle: '',
    timeEstimate: 'Varies (preparation weeks to months, ceremony 1 to several days, integration ongoing)',
    storyCard: [
      'Something happens when a person goes deep enough into themselves that they cannot maintain the story they have been telling. The scaffolding comes down. And in that space, things become visible that ordinary consciousness keeps behind glass.',
      'This quest is about intentional inner journey. That can mean plant medicine ceremony. It can mean a vision quest, a fasting retreat, an extended meditation intensive, a sweat lodge, a dark retreat, or any other form of held practice that creates the conditions for genuine depth. What matters is that it is intentional, supported, and integrated.',
      'These practices have been used by cultures around the world for thousands of years to facilitate healing, initiation, and contact with deeper dimensions of reality. They are not entertainment. They are not shortcuts. Used well, they are among the most powerful catalysts for transformation available to a human being.',
      'Used carelessly, they can harm. The container matters. The preparation matters. Integration matters most of all. A profound experience with no integration is just a story you tell. Integration is the work of taking what you found in the depths and actually living differently because of it.',
      'Whatever you find in the depths belongs partly to you and partly to this community. The regenerative movement needs people who have genuinely been changed. Your integration artifact, shared honestly, is a contribution to the collective intelligence of this game.',
    ],
    storyTeaser: [
      'Something happens when a person goes deep enough into themselves that they cannot maintain the story they have been telling. The scaffolding comes down. And in that space, things become visible that ordinary consciousness keeps behind glass.',
    ],
    howToSteps: [
      { heading: 'Step 1: Choose your practice.', body: 'Identify the form of inner journey you are called to. If you are working with plant medicines, ensure you are doing so legally within your jurisdiction, with appropriate ceremonial support, and with clear intention. If you are doing a vision quest, fasting retreat, or meditation intensive, the same principles apply: container, intention, and support.' },
      { heading: 'Step 2: Prepare intentionally.', body: 'Preparation is not just dietary (though that matters). It is clearing your calendar, telling the people close to you what you are doing, setting a clear intention for what you are entering the journey to meet. Write your intention down. Bring it with you.' },
      { heading: 'Step 3: Enter with good support.', body: 'A genuine guide or facilitator matters enormously. Someone who has walked this path many times, who knows how to hold space for what arises, who will not abandon you when it gets difficult. Do not do a significant inner journey alone without experience.' },
      { heading: 'Step 4: Come back with care.', body: 'The first 24 to 72 hours after a deep journey are critical. Protect them. Do not rush back to work, screens, or social situations. Rest. Write. Walk. Let what happened settle.' },
      { heading: 'Step 5: Integrate over time.', body: 'Genuine integration takes weeks to months. The insights are fragile at first. Journal regularly. Talk with someone who can hold the complexity of what you experienced. Notice where the experience wants to change how you live. Follow those threads.' },
      { heading: 'Step 6: Create and share your artifact.', body: 'Write, record, or otherwise capture a reflection on your journey and its integration. What did you enter with? What did you find? What is different now? Share it with this community at whatever level of depth you choose.' },
    ],
    deliverable: 'A documented reflection on your journey and integration, shared with the community.',
    tips: [
      'Preparation determines outcome more than people expect. How you enter shapes what you find.',
      'Your guide or facilitator is the most important decision you make. More important than the medicine or the practice itself. Do your research.',
      'Integration is not complete when you feel good. It is complete when you live differently. Watch for the moments when the old pattern comes up and you have a new response available. That is integration working.',
      'Not every journey is blissful. Some of the most important ones are the hardest. Difficulty is not failure.',
    ],
    resources: [
      { label: 'Psychedelic Integration Alliance (psychedelicintegration.com) for finding integration therapists and guides', url: '' },
      { label: 'Zendo Project (zendoproject.org) for harm reduction and support frameworks', url: '' },
      { label: 'MAPS (maps.org) for research on therapeutic uses of plant medicines', url: '' },
      { label: 'The Peyote Way, The Psilocybin Solution, and similar tradition-specific resources for ceremony context', url: '' },
    ],
    connections: {
      comesBefore: [0],
      referencedBy: [
        'Comes after: Quests 1-4. A healthy body creates a cleaner container for inner journey',
        'Feeds into: Quest 10 (NVC). What you find in the depths often includes things about how you relate',
      ],
    },
  },
  '9b': {
    id: '9b',
    subtitle: '',
    timeEstimate: '2 to 4 hours (spread across multiple visits)',
    storyCard: [
      'Trees communicate. That sentence would have seemed like poetry thirty years ago. Now it is science. Suzanne Simard\'s research showed that trees in a forest share carbon, water, and chemical signals through mycorrhizal networks underground. Old trees support younger trees, including those of different species. When a tree is stressed or injured, it sends warning compounds through the network. The forest responds.',
      'Peter Wohlleben spent decades as a forester and wrote a book about what he observed when he actually paid attention: trees that grieved when their companions died, that remembered drought years decades later, that slowed their growth to match the pace of a neighbor. None of this is mysticism. It is careful observation of organisms whose timescales and sensory modalities are different from ours.',
      'We are poor at perceiving things that move and communicate at a different speed. But the capacity is there. It just requires slowing down.',
      'This quest asks you to build a real relationship with the trees near you. Not a walk in the woods. A relationship. You return to the same trees over time. You learn to read what you are seeing. You develop the habit of genuine attention rather than passing appreciation.',
      'When you learn to listen to trees, you also learn something about what it means to listen to anything that is not shaped like you.',
    ],
    storyTeaser: [
      'Trees communicate. That sentence would have seemed like poetry thirty years ago. Now it is science. Suzanne Simard\'s research showed that trees in a forest share carbon, water, and chemical signals through mycorrhizal networks underground. Old trees support younger trees, including those of different species. When a tree is stressed or injured, it sends warning compounds through the network. The forest responds.',
    ],
    howToSteps: [
      { heading: 'Step 1: Find your trees.', body: 'Identify two or three trees within easy reach of your daily life. Ideally, find at least one old tree in the oldest accessible forest or parkland near you. The older, the more it has to show you.' },
      { heading: 'Step 2: Visit regularly.', body: 'Return to the same trees at least once a week over the duration of this quest. Same trees. Different weather, different light, different states of your own attention. The relationship builds through repetition.' },
      { heading: 'Step 3: Learn to read what you see.', body: 'Study the basics of tree health: bark patterns, canopy shape, root surface, presence of fungi and lichen, which species share space with which. A local tree identification guide helps. Lichen growing on bark indicates clean air. Bracket fungi at the base indicate root decay. A tree leaning toward the light tells you about the forest structure around it.' },
      { heading: 'Step 4: Practice genuine attention.', body: 'On at least three visits, spend 20 minutes or more doing nothing except being with one tree. Sit at its base. Put your hands on the bark. Follow the branches with your eyes. Notice what changes in your body when you stop moving and start attending.' },
      { heading: 'Step 5: Research the species you are working with.', body: 'Learn the ecology of your trees: how long do they live, how do they reproduce, what animals depend on them, what is their relationship to the soil and the water. Understanding the life of a tree changes what you see when you look at one.' },
      { heading: 'Step 6: Document your relationship.', body: 'Keep a field journal across your visits. Photos, observations, sketches. What did you notice this week that you did not notice last week?' },
      { heading: 'Step 7: Share your account.', body: 'Write or record a piece about your relationship with these specific trees. What did you learn to see? What shifted in how you relate to the living world around you?' },
    ],
    deliverable: 'A documented account of your relationship with specific trees over at least three weeks, including what you learned to see and what changed.',
    tips: [
      'The old-growth forest floor is one of the most complete expressions of a living mycorrhizal network you can walk on. If you have access to any old-growth, go there.',
      'The talking that trees do is primarily chemical and subterranean. You will not hear it. But you can learn to read the effects: the health of the whole stand, the relationships between species, the way the forest allocates resources in hard years.',
      'Slow down more than you think you need to. Most of what we miss in nature we miss because we are moving too fast to perceive it.',
    ],
    resources: [
      { label: 'The Hidden Life of Trees by Peter Wohlleben', url: '' },
      { label: 'Finding the Mother Tree by Suzanne Simard', url: '' },
      { label: 'A local tree identification guide for your bioregion', url: '' },
      { label: 'iNaturalist app (for species ID and mycorrhizal network research)', url: '' },
    ],
    connections: {
      referencedBy: [
        'Pairs with: Quest 8 (Wild Foraging). You are developing a relationship to the same land through different practices',
        'Pairs with: Quest 3 (Healing Whole). Trees are the primary partner in a food forest; understanding them deepens the work',
      ],
    },
  },
  10: {
    id: 10,
    subtitle: 'Speaking from Needs, Not Judgments',
    timeEstimate: 'Ongoing (course + practice)',
    storyCard: [
      'Marshall Rosenberg spent decades studying what happens when people speak to each other honestly. What he found was that most of what we call communication is not really communication at all. It is a series of demands, evaluations, comparisons, and punishments dressed up as conversation.',
      'The dominant languages we have inherited were shaped by cultures of domination. They are built around evaluation (right/wrong, good/bad), moralism (you should, you must), comparison (better than, less than), and denial of responsibility (I had to, I had no choice). These structures make genuine connection nearly impossible while making conflict almost inevitable.',
      'NVC offers a different grammar. Observations instead of evaluations. Feelings instead of interpretations. Needs instead of demands. Requests instead of commands.',
      '"It\'s not what other people do, but the images we create in our heads that produce our anger." Marshall Rosenberg',
      'Violence, Rosenberg argued, is always a result of people convincing themselves that their pain comes from other people, and that those people deserve to be punished. NVC breaks that chain. It routes the pain back to the unmet need underneath it, where it can actually be addressed.',
      'This matters enormously for the ReGen Civics game. We are trying to build new organizations, new governance structures, new communities. All of them will have conflict. All of them will have moments where people feel unseen, unheard, or wronged. The only way through is a practice of communication that can hold that complexity without collapsing into punishment and blame.',
      '"Why would anyone want to be truthful with someone who judges and punishes them?" Marshall Rosenberg',
      'NVC is not soft. It takes more courage than argument. It requires you to name what you actually feel and what you actually need, which most of us have been trained not to do.',
      '"Never walk when you can dance." Marshall Rosenberg\'s grandmother',
    ],
    storyTeaser: [
      'Marshall Rosenberg spent decades studying what happens when people speak to each other honestly. What he found was that most of what we call communication is not really communication at all. It is a series of demands, evaluations, comparisons, and punishments dressed up as conversation.',
    ],
    howToSteps: [
      { heading: 'Step 1: Take the NVC course.', body: 'Find the recommended NVC materials in the Resources section below and watch the attached course. The online courses, Rosenberg\'s books, and the free recordings of his workshops are all valid starting points.' },
      { heading: 'Step 2: Practice the four components.', body: 'Observation, Feeling, Need, Request. Apply them in your daily conversations. Start with low-stakes situations before bringing them into high-stakes ones.' },
      { heading: 'Step 3: Find a practice partner.', body: 'NVC practiced alone is limited. Find someone else to study and practice with. This could be a partner, a friend, or a group. Many cities have NVC practice circles. Or you can go to the forum and seek out a partner who\'s also on this quest and make some friends!' },
      { heading: 'Step 4: Apply in a real situation.', body: 'Bring NVC into a genuine conflict or tension in your life. Not to win. To connect.' },
      { heading: 'Step 5: Reflect and share.', body: 'Write or record a reflection on what you learned. What shifted? Where did it get hard? What would you tell someone just starting?' },
      { heading: 'Step 6: Attend or host a community session.', body: 'The forum will have regular NVC discussion threads. Participate. If there is not a session happening, start one.' },
    ],
    deliverable: 'A written reflection, video, or recorded conversation showing your NVC practice and what it opened up - if you\'re willing, share a moment where it helped you through a challenge.',
    tips: [
      'The hardest part for most people is distinguishing observations from evaluations. Practice this first.',
      '"I feel like you don\'t care about me" is not a feeling. It is an interpretation. "I feel hurt and lonely" is a feeling.',
      'Gratitude is also NVC. Practice expressing gratitude in terms of what your needs were met, not just "thank you." This makes it far more meaningful.',
      'Read: "How might we regularly express our gratitude to those we love?" SEEDS built their entire "gratitude token" economy around this question.',
    ],
    resources: [
      { label: 'Nonviolent Communication: A Language of Life by Marshall Rosenberg', url: '' },
      { label: 'NVC Academy', url: 'https://nvctraining.com' },
      { label: 'Gabor Mate on trauma and communication', url: 'https://www.youtube.com/playlist?list=PL3Xi8vZSmBTRlD8Dnx6a16yeBTaSxKNdS' },
      { label: 'Center for Nonviolent Communication (cnvc.org)', url: '' },
    ],
    connections: {
      referencedBy: [
        'This quest bridges personal healing into collective co-creation',
        'Referenced by: All governance and community quests that follow',
        'Qualifier for: Any stewardship or governance role within the ReGen Civics game',
      ],
    },
  },
  11: {
    id: 11,
    subtitle: '',
    timeEstimate: 'Ongoing study + 1 to 3 group sessions (weeks to months)',
    storyCard: [
      'Every group that tries to work together without a boss eventually hits the same wall. Who makes the final call? How do you handle disagreement? How do you stop a few people from dominating everything? How do you coordinate when there is no authority to appeal to?',
      'These are not unsolvable problems. They are solved, repeatedly, by groups around the world who have developed specific coordination patterns. The patterns have names. They can be learned and applied. Some groups burn through them in a year through conflict and collapse, while others spend generations using them well. The difference is usually whether the patterns were made explicit before the crisis hit.',
      'Holacracy, Sociocracy, and consent-based governance are modern formalizations of much older practices. The indigenous consensus circle, the Quaker clearness committee, the gift economy potlatch, the commons governance of traditional fishing communities. Groups of humans have been solving the coordination problem for as long as humans have existed. We have more tools available than most people know.',
      'This quest is about learning those tools, finding the patterns that fit your context, and actually using them in a real group.',
      'Doing this quest will not make you an expert in group coordination. It will give you a vocabulary, a set of practices, and the beginning of real experience. When conflict comes in the groups you are part of, and it will, you will have something to reach for.',
    ],
    storyTeaser: [
      'Every group that tries to work together without a boss eventually hits the same wall. Who makes the final call? How do you handle disagreement? How do you stop a few people from dominating everything? How do you coordinate when there is no authority to appeal to?',
    ],
    howToSteps: [
      { heading: 'Step 1: Learn the landscape of coordination patterns.', body: 'Study at least two different approaches to non-hierarchical group coordination. Good starting points: Holacracy or Sociocracy (consent-based governance for organizations), Circle Practice for group decision-making, the Commons Governance Principles developed by Elinor Ostrom. Find the Resources section below for entry points.' },
      { heading: 'Step 2: Identify a real group to practice with.', body: 'A project team, a household, a community organization, a ReGen Civics game group. The practice needs real stakes and real people to be useful.' },
      { heading: 'Step 3: Introduce at least one coordination pattern to the group.', body: 'Choose something appropriate to the group\'s size and maturity: a check-in round, a consent decision process, a role-clarity exercise, a retrospective format. Explain why you are introducing it. Try it.' },
      { heading: 'Step 4: Notice what the pattern does and does not do.', body: 'Run at least three sessions using the same pattern before evaluating it. Patterns need iteration to show their value. Ask the group: what worked, what did not, what would we change?' },
      { heading: 'Step 5: Document the pattern and your findings.', body: 'Write up what you did, how the group responded, what the pattern helped with, and what it did not address. This documentation is your contribution to the collective knowledge base.' },
      { heading: 'Step 6: Share your experience.', body: 'Post your write-up in the forum. Others in the game are working on the same problems. Your documented experience is useful.' },
    ],
    deliverable: 'A documented account of a coordination pattern you introduced and practiced in a real group, including reflection on what worked and what you would do differently.',
    tips: [
      'The check-in round is the single most universally useful coordination pattern. Every meeting starts with a brief personal check-in: each person says in one or two sentences how they are arriving. This practice alone changes meeting culture more than almost anything else.',
      'Consent is different from consensus. Consensus requires everyone to agree. Consent requires no one to have a fundamental objection. Consent is much faster and usually better for functioning groups.',
      'The most important governance question is not "what structure do we use" but "how do we make and revisit agreements." Any structure becomes dysfunction if the group cannot update its own rules.',
    ],
    resources: [
      { label: 'Reinventing Organizations by Frederic Laloux (overview of self-organizing companies)', url: '' },
      { label: 'The Sociocracy 3.0 Practical Guide (sociocracy30.org, free online)', url: '' },
      { label: 'Governing the Commons by Elinor Ostrom (the foundational text on commons governance)', url: '' },
      { label: 'NVC by Marshall Rosenberg (communication is the foundation of coordination)', url: '' },
    ],
    connections: {
      comesBefore: [10],
      referencedBy: [
        'Qualifier for: DAO governance roles, land project stewardship, alliance org coordination',
      ],
    },
  },
  12: {
    id: 12,
    subtitle: '',
    timeEstimate: '3 to 5 hours (breathwork session + reflection)',
    storyCard: [
      'The breath is the fastest path to an altered state that most people have access to right now, without anything else, without preparation, without cost.',
      'Breathing changes brain chemistry. Extended intentional breathing affects CO2 and oxygen levels in ways that produce measurable shifts in consciousness: relaxation of the default mode network, a quieting of the internal critic, an expansion of what feels possible. This is why breathwork has been used in healing and ceremony contexts for thousands of years. And it is why combining it with visioning works so well.',
      'When the ordinary logical mind relaxes, the imagination becomes more fluid. The usual objections and anxieties that block genuine visioning go quiet. In that quieter state, it becomes possible to actually feel your way into a future, rather than just thinking about it.',
      'Most people who try to vision a regenerative future end up listing things: solar panels, permaculture gardens, community governance. This is useful but it is not visioning. Genuine visioning is sensory and specific. You are in a place, in a time, experiencing something. What do you hear? What are people doing? What does it feel like to move through that world?',
      'The futures we can feel our way into are different from the futures we can only think about. Felt futures generate different motivations, different designs, different choices.',
      'After a breath session, you can feel your way in. This quest asks you to go there and come back with a report.',
    ],
    storyTeaser: [
      'The breath is the fastest path to an altered state that most people have access to right now, without anything else, without preparation, without cost.',
    ],
    howToSteps: [
      { heading: 'Step 1: Learn the basic breathwork approach you will use.', body: 'Holotropic breathwork, Wim Hof, transformational breathing, or any other intentional breathing practice you are drawn to. If you are new to breathwork, start with a guided online session before doing a full session alone. The Resources section has entry points.' },
      { heading: 'Step 2: Prepare your space.', body: 'Create a comfortable lying-down space where you will not be interrupted for 45 to 90 minutes. Low light, comfortable temperature. Have a journal or recording device nearby for immediately afterward.' },
      { heading: 'Step 3: Set your intention before beginning.', body: 'You are going into this session to vision a specific future: the world 20 years from now, if things go well. Hold that intention lightly as you begin.' },
      { heading: 'Step 4: Do a full breathwork session.', body: 'Follow your chosen method for 30 to 60 minutes. Let the visioning emerge naturally rather than forcing it. You may find yourself somewhere unexpected. Go there.' },
      { heading: 'Step 5: Write or record immediately after.', body: 'While the experience is still fresh, capture everything you can: what you saw, where you were, who was there, what it felt like, what surprised you. Do not edit or interpret yet. Just capture.' },
      { heading: 'Step 6: Reflect and compose your vision document.', body: 'After a day or two, return to your notes. Shape them into a coherent account of the future you visited. Make it sensory and specific. What was the food like? How did people move through public space? What had been healed? Include details that surprised you as well as things you expected.' },
      { heading: 'Step 7: Share it with the community.', body: 'Your vision is a piece of the collective picture we are building together of where we are going.' },
    ],
    deliverable: 'A sensory, specific written or recorded account of a future you visited during and after a breathwork session.',
    tips: [
      'If intense emotions arise during breathwork, stay with them. They are not signs that something is wrong. They are releases. Keep breathing.',
      'The most interesting visions are usually the ones you did not plan. Trust the unexpected details over the expected ones.',
      'Do not drive for at least a few hours after a deep session. Give yourself time to return fully to ordinary consciousness.',
      'You can do this quest with a partner. One person breathes while the other holds space, then you switch. The held experience is often deeper.',
    ],
    resources: [
      { label: 'Wim Hof Method (wimhofmethod.com) for a structured entry-level breathing practice', url: '' },
      { label: 'Holotropic Breathwork by Stanislav Grof and Christina Grof (the foundational approach)', url: '' },
      { label: 'Inner Journeys podcast or YouTube for guided breathwork sessions', url: '' },
    ],
    connections: {
      referencedBy: [
        'Pairs with: Quest 9 (Medicine Journey). Both practices access non-ordinary states for insight and healing',
        'Feeds into: EPIC Quests. The futures you vision here are the ones you build in the EPIC tier',
      ],
    },
  },
  13: {
    id: 13,
    subtitle: '',
    timeEstimate: 'Minimum 3-day fast required for each claim. Extended fasting beyond 3 days is encouraged.',
    storyCard: [
      'The body knows how to heal itself. What it needs, more often than any supplement or intervention, is time to stop processing long enough to do the work.',
      'When you fast, digestion stops. The gut, which uses more energy than almost any other system in the body, goes quiet. That energy gets redirected. Autophagy kicks in: a process by which cells break down and recycle damaged components. Cellular cleanup that the body cannot do while it is busy digesting. Inflammation decreases. Insulin sensitivity improves. The brain, running on ketones instead of glucose, enters a different mode of operation.',
      'None of this is fringe science. Fasting research is mainstream and growing. The 2016 Nobel Prize in Physiology was awarded for autophagy research. Cultures around the world have been practicing intentional fasting for thousands of years: Ramadan, Yom Kippur, Lent, Buddhist fasting traditions, indigenous vision quest fasts. They did not have the biochemistry, but they had the observation that something important happened when people stopped eating.',
      'The experience is not comfortable, at least not at first. Hunger is real. The second day is often the hardest. Around day three, something shifts. The hunger quiets. The mind gets cleaner. There is a clarity that is hard to describe until you have been there.',
      'This quest is repeatable because the practice compounds. Each fast teaches you something different. Early fasts are about the physical experience: hunger, energy, the mechanics of getting through. Later fasts, once the body has adapted and the fear is gone, become about something else. What remains when the usual drives go quiet.',
      'The minimum for this quest is a clean 3-day water fast. That is the threshold where something real opens up. Earlier fasts are preparation. Three days is initiation. If you extend beyond three days, something more becomes available still.',
    ],
    storyTeaser: [
      'The body knows how to heal itself. What it needs, more often than any supplement or intervention, is time to stop processing long enough to do the work.',
    ],
    howToSteps: [
      { heading: 'Step 1: Choose your fast.', body: 'Minimum for this quest: a clean 3-day water fast (water and herbal tea only, no calories). This is the minimum required to claim tokens. If you can extend beyond 3 days, do. Whatever you choose, set your intention clearly before you begin.' },
      { heading: 'Step 2: Prepare your body.', body: 'In the days before a longer fast, reduce processed foods, sugar, and caffeine gradually. A clean transition into the fast reduces discomfort significantly. For a 24-hour fast, less preparation is needed.' },
      { heading: 'Step 3: Prepare your environment.', body: 'Tell the people around you what you are doing. Clear your schedule of high-demand obligations. Have water, herbal tea, and electrolytes available. Make sure you have somewhere to rest if needed.' },
      { heading: 'Step 4: Fast with intention.', body: 'Note how you are feeling at the start, middle, and end. What is your energy? Your mood? Your clarity? Your relationship to hunger? Hunger comes in waves. When it comes, observe it. It passes. What remains when it has passed?' },
      { heading: 'Step 5: Break your fast gently.', body: 'Start with fruit, diluted juice, or broth. Give your digestive system a day to rebuild before returning to normal meals. The re-entry is as important as the fast.' },
      { heading: 'Step 6: Write your reflection.', body: 'Each time you complete a fast, write a brief account. What happened in your body? What happened in your mind? What did you notice that surprised you? Over multiple fasts, these reflections become a record of a practice.' },
    ],
    deliverable: 'A reflection document for each completed fast: dates, duration, key observations, and what shifted.',
    tips: [
      'The hardest part of any fast is the first four to six hours. Once past that, hunger becomes more manageable and the clarity begins.',
      'Coffee and tea without anything added do not appear to significantly break the cellular benefits of fasting. If giving up coffee makes a fast impossible, keep it. The fast matters more than the coffee.',
      'People with certain medical conditions (diabetes, eating disorder history, pregnancy) should consult a doctor before fasting. Take this seriously.',
      'Dry fasting (no water) can be practiced by experienced fasters for shorter periods but is significantly more intense. Do not start there.',
      'Extended fasting requires electrolytes. Add a small amount of salt and potassium to your water on days 2 and beyond or use an electrolyte supplement without calories.',
    ],
    resources: [
      { label: 'The Complete Guide to Fasting by Jason Fung (accessible overview of fasting science and practice)', url: '' },
      { label: 'Fasting and Eating for Health by Joel Fuhrman (natural hygiene perspective on fasting)', url: '' },
      { label: 'Dr. Valter Longo\'s research on longevity and fasting (search: Longo fasting-mimicking diet)', url: '' },
    ],
    connections: {
      referencedBy: [
        'Pairs with: Quest 1 (Potions). Fasting clears space that the living foods then fill',
        'Pairs with: Quest 9 (Medicine Journey). Extended fasts produce altered states and deep inner access',
        'Reinforces: All quests. The discipline and clarity of fasting supports every other practice in the game',
      ],
    },
  },
  14: {
    id: 14,
    subtitle: '',
    timeEstimate: '1 moon cycle (every other day, 1 hour per session, ~15 sessions)',
    storyCard: [
      'Most of us live from the neck up. We think our way through the day, override the body\'s signals, and only pay attention when something breaks. This quest reverses that pattern. For one full moon cycle, every other day, you spend an hour in direct conversation with your body. You scan from feet to crown, you find the tension, and you send love there. Actual love, the way you would hold a child or a hurt animal. The body responds to this. Tension that has lived in the same places for years begins to loosen. Pain that seemed permanent starts to shift. By the end of the cycle, many people report that their body has started speaking to them in ways they can finally hear.',
    ],
    storyTeaser: [
      'Most of us live from the neck up. We think our way through the day, override the body\'s signals, and only pay attention when something breaks. This quest reverses that pattern. For one full moon cycle, every other day, you spend an hour in direct conversation with your body. You scan from feet to crown, you find the tension, and you send love there. Actual love, the way you would hold a child or a hurt animal. The body responds to this. Tension that has lived in the same places for years begins to loosen. Pain that seemed permanent starts to shift. By the end of the cycle, many people report that their body has started speaking to them in ways they can finally hear.',
    ],
    howToSteps: [
    ],
    deliverable: '',
    tips: [
      'The first 3-4 sessions often feel like nothing is happening. That is normal. The shift usually comes around session 5-7.',
      'If you find a spot that triggers strong emotion, stay with it gently. Crying, laughing, or shaking are all the body releasing stored tension.',
      'Some people fall asleep during early sessions. If it keeps happening, try sitting upright.',
      'Do not skip sessions to "make up" two in one day. The rest day between sessions is part of the practice.',
    ],
    resources: [
    ],
    connections: {
      referencedBy: [
        'Pairs with: Quest 13 (Fasting) - both practices teach you to listen to the body instead of overriding it',
        'Pairs with: Quest 8 (Medicine Journey) - body scanning builds the awareness muscle that makes inner exploration safer',
        'Reinforces: All quests - a body that feels heard and loved has more energy for everything else',
      ],
    },
  },
};
