/**
 * /ship/giveaway/rules - Official rules for the Free Voyage Giveaway.
 *
 * Gated by GIVEAWAY_RULES_APPROVED (read through shipGiveaway.stats.rulesApproved).
 * Until Oregon counsel signs off and Rye flips the flag, the page shows a
 * placeholder and the entry button on /ship/giveaway is disabled, so this deploys
 * ahead of the legal review. Word discipline: "entries" and "the draw", never
 * "raffle" or "tickets". Free sweepstakes, not a raffle.
 */
import { SEO } from "@/components/SEO";
import { PageWrapper } from "@/components/PageWrapper";
import { ScrollText } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { ShipSection, ShipEyebrow, ShipNavRow } from "./shipShared";

const RULES: Array<{ heading: string; body: React.ReactNode }> = [
  {
    heading: "No purchase necessary",
    body: (
      <p className="font-semibold">
        No purchase or donation is necessary to enter or win. A purchase or donation will not increase your chances of
        winning. Void where prohibited.
      </p>
    ),
  },
  {
    heading: "1. Sponsor",
    body: (
      <p>
        Church of the Regenerative Earth, also doing business as ReGen Civics, of Ashland, Oregon (the "Sponsor"). EIN
        42-3198293.
      </p>
    ),
  },
  {
    heading: "2. Promotion period",
    body: (
      <p>
        Entries open Monday, July 27, 2026 at 9:00 am Pacific and close Sunday, September 6, 2026 at 11:59 pm Pacific.
        Entries received outside this window are void.
      </p>
    ),
  },
  {
    heading: "3. Eligibility",
    body: (
      <p>
        Open to legal residents of the 50 United States and the District of Columbia who are 18 years of age or older
        (or the age of majority in their state, whichever is greater) at the time of entry. Employees, ministers,
        officers, stewards, and Keepers of the Sponsor, contractors on the ReGen Ship program, and members of their
        immediate households are not eligible. Void where prohibited by law.
      </p>
    ),
  },
  {
    heading: "4. How to enter",
    body: (
      <>
        <p className="mb-2">
          <strong>Base entry (free).</strong> Submit your email address at regencivics.earth/ship/giveaway and confirm
          it through the verification email. One base entry per person. One email address per person.
        </p>
        <p className="mb-2">
          <strong>Optional bonus entries.</strong> Never required. Base entrants and bonus entrants are drawn from the
          same pool, with odds proportional to the number of entries held.
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Five additional entries for each friend who enters through your personal referral link and confirms their email, up to a total of forty entries from referrals.</li>
          <li>Three additional entries for nominating a regenerative land project through the entry page.</li>
          <li>Two additional entries for completing any action on the Ship's Quest at regencivics.earth/ship/quest.</li>
          <li>One additional entry each, one per platform, for following the Sponsor on Instagram or YouTube, self-reported on the entry page.</li>
        </ul>
        <p className="mt-2">
          No purchase, payment, donation, or voyage booking is required for any entry method, and none affects the odds.
          Entries generated by bots, scripts, or duplicate accounts are disqualified.
        </p>
      </>
    ),
  },
  {
    heading: "5. Prize",
    body: (
      <>
        <p className="mb-2">
          One grand prize: a seven-night voyage aboard the ReGen Ship, departing from and returning to Ashland, Oregon
          (Monday 3:00 pm boarding to Sunday 11:00 am return), redeemable on an available, mutually agreed week between
          September 14, 2026 and June 30, 2027, subject to the published booking calendar and blackout dates. Includes
          1,000 road miles and a pre-departure orientation. Approximate retail value: $2,093.
        </p>
        <p className="mb-2">
          The prize does not include fuel, mileage beyond 1,000 miles (billed at $0.50 per mile), transportation to or
          from Ashland, food, the refundable security deposit ($1,500, held and returned per the Voyage Covenant), or any
          cost outside the Voyage Covenant and Rental Terms. The winner and crew must satisfy all standard voyage
          requirements, including at least one licensed, platform-approved driver aged 25 or older, and agreement to the
          Voyage Covenant, including the clean-vessel rule (meat-free, alcohol-free, smoke-free aboard). The approved
          driver may be a qualified member of the winner's crew. The prize is not transferable and not redeemable for
          cash. If the winner cannot satisfy the voyage requirements or complete the platform booking steps, the prize
          passes to a backup winner.
        </p>
        <p>
          Secondary prizes, drawn from the same pool after the grand prize: three Season 2 fast-track project sessions;
          five gifted three-month Root circle memberships; twenty sticker packs; and two thirty-minute calls with the
          Sponsor's founder. Total approximate retail value of all prizes: about $2,788.
        </p>
      </>
    ),
  },
  {
    heading: "6. Winner selection and notification",
    body: (
      <p>
        Winners are selected by a random drawing from all confirmed entries on or about September 8, 2026, conducted by
        the Sponsor. Odds of winning depend on the total number of entries received. Winners are notified by email and
        must respond within five days. The grand prize winner must also complete, sign, and return an Affidavit of
        Eligibility and a Liability and Publicity Release within seven days of notification. Failure to respond,
        ineligibility, or refusal forfeits the prize, and a backup winner is drawn.
      </p>
    ),
  },
  {
    heading: "7. Taxes",
    body: (
      <p>
        The grand prize winner is responsible for all applicable taxes. The Sponsor will issue IRS Form 1099-MISC for
        prizes at or above the reporting threshold.
      </p>
    ),
  },
  {
    heading: "8. Publicity",
    body: (
      <p>
        Except where prohibited, acceptance of a prize is permission for the Sponsor to use the winner's first name, last
        initial, and general location in campaign announcements, with no further payment. A winner may decline publicity
        beyond the legally required winners list.
      </p>
    ),
  },
  {
    heading: "9. Platform releases",
    body: (
      <p>
        This promotion is in no way sponsored, endorsed, administered by, or associated with Instagram, Facebook, Meta
        Platforms Inc., TikTok, YouTube, Google LLC, or Reddit. Entrants release each of those platforms from all
        liability connected with this promotion. Entry occurs only at regencivics.earth, never through any social
        platform mechanic.
      </p>
    ),
  },
  {
    heading: "10. General conditions",
    body: (
      <p>
        The Sponsor may disqualify any entrant who tampers with the entry process or violates these rules. If the
        promotion cannot run as planned for reasons beyond the Sponsor's control, the Sponsor may suspend or modify it,
        and if it is ended early, will draw winners from eligible entries received before then. Entrant data is used per
        the Sponsor's privacy policy. Entering adds you to the Sponsor's email list, which you may leave at any time
        without affecting your entries.
      </p>
    ),
  },
  {
    heading: "11. Disputes",
    body: (
      <p>
        These rules are governed by the laws of the State of Oregon. Any dispute is resolved individually, without class
        action, in the state or federal courts of Jackson County, Oregon, after good-faith mediation.
      </p>
    ),
  },
  {
    heading: "12. Winners list",
    body: (
      <p>
        For the names of winners, send a self-addressed stamped envelope to the Sponsor's address within 60 days of the
        drawing.
      </p>
    ),
  },
];

export default function ShipGiveawayRules() {
  const stats = trpc.shipGiveaway.stats.useQuery(undefined, { staleTime: 30_000 });
  const rulesApproved = stats.data?.rulesApproved ?? false;
  const loading = stats.isLoading;

  return (
    <PageWrapper>
      <SEO
        title="Free Voyage Giveaway Rules"
        description="Official rules for the ReGen Ship Free Voyage Giveaway. No purchase or donation necessary. Free entry only. Odds depend on entries received."
        url="/ship/giveaway/rules"
      />
      <ShipNavRow current="/ship/giveaway" />

      <ShipSection>
        <ShipEyebrow>Official rules</ShipEyebrow>
        <h1 className="text-3xl md:text-4xl font-bold mb-4 flex items-center gap-3">
          <ScrollText className="w-8 h-8 text-[#4a7c59] dark:text-[#7dd87d] shrink-0" aria-hidden="true" />
          Free Voyage Giveaway rules
        </h1>

        {loading ? (
          <p className="text-foreground/70">Loading the rules...</p>
        ) : rulesApproved ? (
          <div className="space-y-8 max-w-3xl mt-4">
            {RULES.map((r) => (
              <div key={r.heading}>
                <h2 className="text-xl font-semibold mb-2">{r.heading}</h2>
                <div className="text-foreground/85 space-y-2">{r.body}</div>
              </div>
            ))}
          </div>
        ) : (
          <div className="max-w-2xl rounded-2xl border border-[#d4a574]/50 bg-[#d4a574]/10 p-6 mt-4">
            <p className="text-foreground/85 mb-2">
              The official rules publish here before entries open. They are in final review now.
            </p>
            <p className="text-sm text-foreground/70">
              When they are live, you can enter free with your email at{" "}
              <Link href="/ship/giveaway" className="underline underline-offset-2">
                the giveaway page
              </Link>
              . No purchase or donation is ever necessary.
            </p>
          </div>
        )}
      </ShipSection>
    </PageWrapper>
  );
}
