/**
 * The Galley cookbook: formula cards for the ReGen Ship (/ship/galley).
 *
 * Canonical here in shared/ so both the client (cookbook grid, remixer) and the
 * server (the deterministic remix engine in server/lib/galley-remix.ts, and its
 * tests) read the same cards. client/src/data/galleyCards.ts re-exports this.
 *
 * These are "build your own" formulas, not rigid recipes: a base, some fillings,
 * toppings, and a sauce, plus a loose method and one regenerative line. All
 * ingredients assume organic and local where the road allows.
 *
 * Voice (STEERING section 1): no em-dashes, no contrast framing, no AI filler.
 * Health-adjacent copy stays factual and invitational, never a medical claim.
 */

export type GalleyTrack = "table" | "reset"; // reset = 100% raw safe

export type GalleyCategory =
  | "morning"
  | "midday"
  | "taco"
  | "sushi"
  | "snack"
  | "sauce";

export type GalleyCard = {
  slug: string;
  name: string;
  category: GalleyCategory;
  /** Which tracks this card fits. A cooked card is table-only. */
  tracks: GalleyTrack[];
  /** true = fully raw (fits the Deeper Reset). */
  raw: boolean;
  base: string[]; // pick-one or combine
  fillings: string[];
  toppings: string[];
  sauce: string[];
  /** 1 to 2 sentences, loose. */
  method: string;
  /** one regenerative line. */
  why: string;
};

const BOTH: GalleyTrack[] = ["table", "reset"];
const TABLE_ONLY: GalleyTrack[] = ["table"];

export const GALLEY_CARDS: GalleyCard[] = [
  // ── Mornings (all raw, both tracks) ─────────────────────────────────────────
  {
    slug: "watermelon-wake-up-plate",
    name: "Watermelon Wake-Up Plate",
    category: "morning",
    tracks: BOTH,
    raw: true,
    base: ["ripe watermelon slabs"],
    fillings: [],
    toppings: ["lime", "mint", "flaky salt", "chili"],
    sauce: [],
    method: "Slice thick, squeeze lime, tear mint over the top. Add a pinch of salt and a little chili if you like it.",
    why: "Pure hydration, nothing to cook, nothing to waste.",
  },
  {
    slug: "citrus-sunrise-bowl",
    name: "Citrus Sunrise Bowl",
    category: "morning",
    tracks: BOTH,
    raw: true,
    base: ["oranges", "grapefruit", "tangerine"],
    fillings: [],
    toppings: ["pomegranate", "mint", "hemp seeds"],
    sauce: [],
    method: "Segment the citrus right over a bowl so you catch all the juice.",
    why: "Living vitamin C, straight from a peel-in fruit.",
  },
  {
    slug: "peach-berry-ripeness-bowl",
    name: "Peach and Berry Ripeness Bowl",
    category: "morning",
    tracks: BOTH,
    raw: true,
    base: ["peaches", "nectarines"],
    fillings: ["blueberries", "raspberries"],
    toppings: ["basil", "soaked chia"],
    sauce: [],
    method: "Slice the softest fruit, scatter the berries, let it rest five minutes so the juices come out.",
    why: "Eat it at peak ripeness, and save the pits and seeds for the chest.",
  },
  {
    slug: "morning-green-tonic",
    name: "Morning Green Tonic",
    category: "morning",
    tracks: BOTH,
    raw: true,
    base: ["cucumber", "celery", "green apple", "lemon"],
    fillings: ["ginger", "parsley"],
    toppings: [],
    sauce: [],
    method: "Blend and strain, or run it through a juicer.",
    why: "Cooling and alkaline, a clean way to open the day.",
  },
  {
    slug: "melon-agua-fresca",
    name: "Melon Agua Fresca",
    category: "morning",
    tracks: BOTH,
    raw: true,
    base: ["cantaloupe", "honeydew", "water", "lime"],
    fillings: [],
    toppings: ["mint"],
    sauce: [],
    method: "Blend the melon with water and lime, then pour it over ice.",
    why: "Turns an over-ripe melon into a pitcher for the whole crew.",
  },

  // ── Midday (mostly raw, both tracks) ────────────────────────────────────────
  {
    slug: "deep-sanctuary-salad",
    name: "Deep Sanctuary Salad",
    category: "midday",
    tracks: BOTH,
    raw: true,
    base: ["leafy greens", "cabbage"],
    fillings: ["cucumber", "tomato", "avocado", "sprouts", "carrot"],
    toppings: ["seeds", "herbs", "dulse"],
    sauce: ["lemon-tahini", "citrus-herb"],
    method: "Get out the biggest bowl aboard, layer heaviest to lightest, and toss it at the table.",
    why: "The everyday plate, endlessly remixable from whatever the market gave you.",
  },
  {
    slug: "rainbow-slaw",
    name: "Rainbow Slaw",
    category: "midday",
    tracks: BOTH,
    raw: true,
    base: ["cabbage", "carrot", "beet"],
    fillings: ["apple", "cilantro"],
    toppings: [],
    sauce: ["miso-ginger", "lime-tahini"],
    method: "Shred everything fine, salt it lightly, let it sit ten minutes, then dress it.",
    why: "Keeps for days aboard, and it is better on day two.",
  },
  {
    slug: "signature-chia-bowl",
    name: "Signature Chia Bowl",
    category: "midday",
    tracks: BOTH,
    raw: true,
    base: ["chia", "coconut milk"],
    fillings: [],
    toppings: ["peach", "berries", "banana", "coconut flakes", "date syrup"],
    sauce: [],
    method: "Soak 3 tablespoons chia in 1 cup coconut milk overnight. Stir it at night so it does not clump, and wake up to pudding.",
    why: "The ship's calling card, one jar per crew member.",
  },
  {
    slug: "chia-parfait-variations",
    name: "Chia Parfait Variations",
    category: "midday",
    tracks: BOTH,
    raw: true,
    base: ["chia", "coconut milk"],
    fillings: ["mango", "kiwi", "pomegranate", "cacao", "banana"],
    toppings: [],
    sauce: [],
    method: "Take the chia base and layer it with fruit in a jar, a new combination each morning.",
    why: "Same jar, a new mood every day.",
  },
  {
    slug: "green-power-smoothie",
    name: "Green Power Smoothie",
    category: "midday",
    tracks: BOTH,
    raw: true,
    base: ["banana", "mango", "spinach", "kale", "coconut water"],
    fillings: ["hemp seeds", "ginger"],
    toppings: [],
    sauce: [],
    method: "Blend it all cold until smooth.",
    why: "Greens you will not taste, fuel you will feel.",
  },
  {
    slug: "tropical-recovery-smoothie",
    name: "Tropical Recovery Smoothie",
    category: "midday",
    tracks: BOTH,
    raw: true,
    base: ["pineapple", "mango", "orange", "coconut milk"],
    fillings: ["turmeric", "lime"],
    toppings: [],
    sauce: [],
    method: "Blend cold and drink it fresh.",
    why: "After a hike or a swim, the sweet reset.",
  },
  {
    slug: "stuffed-avocado-boats",
    name: "Stuffed Avocado Boats",
    category: "midday",
    tracks: BOTH,
    raw: true,
    base: ["avocado"],
    fillings: ["tomato", "corn", "cucumber", "red onion"],
    toppings: ["cilantro", "lime", "hemp seeds"],
    sauce: [],
    method: "Halve the avocados, scoop a little hollow, fill them, and squeeze lime over the top.",
    why: "A no-cook lunch that looks like a feast.",
  },
  {
    slug: "cucumber-zucchini-noodle-bowl",
    name: "Cucumber or Zucchini Noodle Bowl",
    category: "midday",
    tracks: BOTH,
    raw: true,
    base: ["cucumber", "zucchini"],
    fillings: ["cherry tomato", "olives", "basil"],
    toppings: [],
    sauce: ["lemon-herb", "cashew cream"],
    method: "Spiralize the cucumber or zucchini, salt lightly, drain a few minutes, then dress.",
    why: "Pasta feeling, fully raw.",
  },

  // ── Taco night (mostly raw, both tracks) ────────────────────────────────────
  {
    slug: "cabbage-wrap-tacos",
    name: "Cabbage-Wrap Tacos",
    category: "taco",
    tracks: BOTH,
    raw: true,
    base: ["cabbage", "lettuce"],
    fillings: ["walnut chorizo", "marinated mushroom"],
    toppings: ["mango salsa", "cilantro", "lime"],
    sauce: ["cashew crema"],
    method: "Use whole cabbage or lettuce leaves as the shells, then load them with your fillings.",
    why: "The fully raw taco, crunch included.",
  },
  {
    slug: "corn-tortilla-tacos",
    name: "Corn-Tortilla Tacos",
    category: "taco",
    tracks: TABLE_ONLY,
    raw: false,
    base: ["corn tortillas"],
    fillings: ["walnut chorizo", "marinated mushroom"],
    toppings: ["mango salsa", "cilantro", "lime"],
    sauce: ["cashew crema"],
    method: "Warm organic corn tortillas on a low flame, then fill them.",
    why: "The small cooked treat, still plant and still organic.",
  },
  {
    slug: "walnut-sunflower-chorizo",
    name: "Walnut-Sunflower Chorizo",
    category: "taco",
    tracks: BOTH,
    raw: true,
    base: ["walnuts", "sunflower seeds"],
    fillings: ["sun-dried tomato"],
    toppings: ["cumin", "smoked paprika"],
    sauce: [],
    method: "Soak the walnuts and sunflower seeds, then pulse them coarse with cumin, smoked paprika, and sun-dried tomato. Do not puree it.",
    why: "Raw, savory, protein-rich taco meat.",
  },
  {
    slug: "mushroom-marinated-filling",
    name: "Mushroom-Marinated Filling",
    category: "taco",
    tracks: BOTH,
    raw: true,
    base: ["mushrooms"],
    fillings: [],
    toppings: [],
    sauce: ["tamari", "lime", "olive oil"],
    method: "Slice the mushrooms, massage them in tamari, lime, and a little olive oil, and rest twenty minutes. They soften like they were cooked.",
    why: "Umami without the stove.",
  },
  {
    slug: "mango-jicama-salsa",
    name: "Mango-Jicama Salsa",
    category: "taco",
    tracks: BOTH,
    raw: true,
    base: ["mango", "jicama", "cucumber"],
    fillings: ["red onion", "cilantro", "jalapeno"],
    toppings: ["lime"],
    sauce: [],
    method: "Dice it all small and toss with lime.",
    why: "A bright topping for any taco or bowl.",
  },
  {
    slug: "taco-sauces",
    name: "Taco Sauces",
    category: "sauce",
    tracks: BOTH,
    raw: true,
    base: ["cashew crema", "avocado-tomatillo", "chipotle-cashew"],
    fillings: [],
    toppings: [],
    sauce: ["cashew", "lime", "tomatillo", "chipotle"],
    method: "Cashew crema is soaked cashews blended with lime, salt, and water. Avocado-tomatillo and chipotle-cashew work the same way with those swaps.",
    why: "Three sauces turn the same fillings into three different dinners.",
  },

  // ── Make-your-own sushi (mostly raw, both tracks) ───────────────────────────
  {
    slug: "cauliflower-rice-base",
    name: "Cauliflower Rice Base",
    category: "sushi",
    tracks: BOTH,
    raw: true,
    base: ["cauliflower"],
    fillings: [],
    toppings: [],
    sauce: ["rice vinegar", "date syrup"],
    method: "Pulse the cauliflower fine, squeeze it dry in a towel, then season with rice vinegar and a little date syrup.",
    why: "The raw stand-in for rice, lighter and alive.",
  },
  {
    slug: "nori-hand-rolls",
    name: "Nori Hand Rolls",
    category: "sushi",
    tracks: BOTH,
    raw: true,
    base: ["nori", "cauliflower rice"],
    fillings: ["avocado", "cucumber", "carrot", "mango", "sprouts", "marinated mushroom"],
    toppings: [],
    sauce: ["tamari"],
    method: "Cone a sheet of nori, fill it, and eat it with your hands.",
    why: "Dinner as a group activity, everyone rolls their own.",
  },
  {
    slug: "rainbow-veggie-rolls",
    name: "Rainbow Veggie Rolls",
    category: "sushi",
    tracks: BOTH,
    raw: true,
    base: ["nori", "cauliflower rice"],
    fillings: ["cucumber", "carrot", "avocado", "red onion"],
    toppings: [],
    sauce: ["tamari"],
    method: "Lay nori and cauliflower rice on a mat, line up thin-cut vegetables, roll tight, wet the seam, and slice with a sharp wet knife.",
    why: "The showpiece plate from a market haul.",
  },
  {
    slug: "watermelon-tomato-poke-bowl",
    name: "Watermelon or Tomato Poke Bowl",
    category: "sushi",
    tracks: BOTH,
    raw: true,
    base: ["watermelon", "tomato"],
    fillings: ["cauliflower rice", "leafy greens"],
    toppings: ["avocado", "cucumber", "scallion", "sesame"],
    sauce: ["tamari", "sesame", "ginger"],
    method: "Cube the watermelon or tomato and marinate it in tamari, sesame, and ginger, then spoon it over cauliflower rice or greens.",
    why: "The tuna that grew in the valley.",
  },
  {
    slug: "sushi-dips",
    name: "Sushi Dips",
    category: "sauce",
    tracks: BOTH,
    raw: true,
    base: ["tamari-ginger", "spicy cashew", "coconut-lime"],
    fillings: [],
    toppings: [],
    sauce: ["tamari", "ginger", "cashew", "coconut", "lime"],
    method: "Whisk tamari with grated ginger for the classic, blend cashews with chili for the spicy one, and stir coconut with lime for the bright one.",
    why: "The dip makes the roll.",
  },

  // ── Snacks and sweets (all raw, both tracks) ────────────────────────────────
  {
    slug: "date-nut-energy-bites",
    name: "Date-Nut Energy Bites",
    category: "snack",
    tracks: BOTH,
    raw: true,
    base: ["dates", "almonds", "walnuts"],
    fillings: ["cacao"],
    toppings: ["salt"],
    sauce: [],
    method: "Pulse the dates and nuts with cacao and a pinch of salt, roll into balls, and chill if you can.",
    why: "Trail fuel for the hike to the waterfall.",
  },
  {
    slug: "frozen-banana-nice-cream",
    name: "Frozen Banana Nice Cream",
    category: "snack",
    tracks: BOTH,
    raw: true,
    base: ["banana"],
    fillings: ["berries", "mango", "cacao"],
    toppings: [],
    sauce: [],
    method: "Blend frozen bananas on their own or with a little fruit until it turns to soft-serve.",
    why: "Ice cream texture, one ingredient, zero waste.",
  },
  {
    slug: "chia-fresca-pops",
    name: "Chia Fresca Pops",
    category: "snack",
    tracks: BOTH,
    raw: true,
    base: ["chia", "coconut water"],
    fillings: ["fruit juice"],
    toppings: [],
    sauce: [],
    method: "Stir chia into coconut water and fruit juice, then freeze it in any cup with a stick.",
    why: "Hydration you can hold on a hot day.",
  },
  {
    slug: "fruit-nut-board",
    name: "Fruit and Nut Board",
    category: "snack",
    tracks: BOTH,
    raw: true,
    base: ["fruit"],
    fillings: ["soaked nuts", "cultured cashew cheese", "dates"],
    toppings: [],
    sauce: [],
    method: "Slice ripe fruit and arrange it with soaked nuts, cashew cheese, and dates.",
    why: "The abundant table, arranged like treasure.",
  },

  // ── Sauces, dressings, ferments (the flavor engine) ─────────────────────────
  {
    slug: "the-flavor-engine",
    name: "The Flavor Engine",
    category: "sauce",
    tracks: BOTH,
    raw: true,
    base: ["cashew", "cabbage"],
    fillings: ["lemon", "salt"],
    toppings: [],
    sauce: ["lemon-tahini", "citrus-herb", "miso-ginger"],
    method: "Keep everyday dressings ready (lemon-tahini, citrus-herb, miso-ginger). Blend soaked cashews with lemon and salt for a cultured cheese and rest it a day. For a quick kraut, massage shredded cabbage with salt and jar it two to five days.",
    why: "Living ferments seed the compost and the gut alike, and a good sauce makes any pile of vegetables a meal.",
  },
];

/**
 * Ingredient normalization: canonical token -> the surface substrings a crew
 * might log ("roma tomato", "ripe watermelon slabs"). The remix engine matches a
 * haul against a card's base/fillings/toppings/sauce through these tokens, so a
 * loosely-typed haul still finds the right dishes.
 */
export const INGREDIENT_ALIASES: Record<string, string[]> = {
  watermelon: ["watermelon"],
  cantaloupe: ["cantaloupe"],
  honeydew: ["honeydew"],
  melon: ["melon"],
  orange: ["orange", "tangerine", "mandarin", "citrus"],
  grapefruit: ["grapefruit"],
  lemon: ["lemon"],
  lime: ["lime"],
  peach: ["peach"],
  nectarine: ["nectarine"],
  apricot: ["apricot"],
  plum: ["plum"],
  apple: ["apple"],
  pear: ["pear"],
  grape: ["grape"],
  banana: ["banana"],
  mango: ["mango"],
  pineapple: ["pineapple"],
  kiwi: ["kiwi"],
  pomegranate: ["pomegranate"],
  blueberry: ["blueberry", "blueberries"],
  raspberry: ["raspberry", "raspberries"],
  strawberry: ["strawberry", "strawberries"],
  berry: ["berry", "berries", "blackberry", "blackberries"],
  fig: ["fig"],
  date: ["date", "dates"],
  greens: ["greens", "lettuce", "spinach", "kale", "arugula", "chard", "mixed greens", "salad greens", "romaine"],
  spinach: ["spinach"],
  kale: ["kale"],
  lettuce: ["lettuce", "romaine"],
  cabbage: ["cabbage"],
  cucumber: ["cucumber"],
  zucchini: ["zucchini", "courgette"],
  tomato: ["tomato", "tomatoes"],
  "cherry tomato": ["cherry tomato", "grape tomato"],
  tomatillo: ["tomatillo"],
  avocado: ["avocado"],
  carrot: ["carrot"],
  beet: ["beet"],
  celery: ["celery"],
  "red onion": ["red onion"],
  onion: ["onion", "scallion", "green onion"],
  scallion: ["scallion", "green onion"],
  jicama: ["jicama"],
  corn: ["corn"],
  "green bean": ["green bean", "green beans"],
  eggplant: ["eggplant", "aubergine"],
  pepper: ["pepper", "bell pepper", "peppers"],
  jalapeno: ["jalapeno", "jalapeño"],
  chili: ["chili", "chile", "chilli"],
  mushroom: ["mushroom", "mushrooms"],
  cauliflower: ["cauliflower"],
  squash: ["squash", "pumpkin"],
  sprouts: ["sprout", "sprouts"],
  radish: ["radish"],
  asparagus: ["asparagus"],
  peas: ["pea", "peas"],
  ginger: ["ginger"],
  turmeric: ["turmeric"],
  garlic: ["garlic"],
  basil: ["basil"],
  mint: ["mint"],
  cilantro: ["cilantro", "coriander"],
  parsley: ["parsley"],
  herbs: ["herb", "herbs"],
  chia: ["chia"],
  hemp: ["hemp"],
  sesame: ["sesame", "tahini"],
  flax: ["flax", "flaxseed"],
  seeds: ["seed", "seeds", "sunflower", "pumpkin seed"],
  sunflower: ["sunflower"],
  walnut: ["walnut", "walnuts"],
  almond: ["almond", "almonds"],
  cashew: ["cashew", "cashews"],
  nuts: ["nut", "nuts", "pecan", "macadamia"],
  coconut: ["coconut"],
  olive: ["olive", "olives"],
  "olive oil": ["olive oil"],
  dulse: ["dulse", "seaweed", "kelp"],
  nori: ["nori"],
  tamari: ["tamari", "soy sauce", "soy"],
  miso: ["miso"],
  "rice vinegar": ["rice vinegar", "vinegar"],
  cacao: ["cacao", "cocoa", "chocolate"],
  "date syrup": ["date syrup", "maple", "agave"],
  "sun-dried tomato": ["sun-dried tomato", "sundried tomato"],
  cumin: ["cumin"],
  "smoked paprika": ["smoked paprika", "paprika"],
  chipotle: ["chipotle"],
  salt: ["salt"],
  "corn tortillas": ["tortilla", "tortillas"],
  "fruit juice": ["juice"],
};

/**
 * Voyage-season staples (Rogue Valley summer) the engine suggests when a haul is
 * thin. Canonical tokens that unlock the most cards. Kept short and abundant.
 */
export const SEASONAL_STAPLES: string[] = [
  "watermelon",
  "peach",
  "tomato",
  "cucumber",
  "avocado",
  "greens",
  "cabbage",
  "mango",
  "lime",
  "banana",
];
