/**
 * Post-process the raw CORE illustrations: crop to each asset's aspect, resize to
 * the registry widths, export WebP + AVIF, compute a tiny blurred LQIP data URI,
 * upload everything to R2 (assets.regencivics.earth/core/...), and write
 * client/src/pages/core/asset-manifest.json so CoreImage switches from fallback
 * to the real illustration.
 *
 * Runs AFTER scripts/generate-core-assets.ts. Uploading needs the R2 creds
 * (AWS_BUCKET_NAME, AWS_REGION, AWS_ENDPOINT_URL, AWS_ACCESS_KEY_ID,
 * AWS_SECRET_ACCESS_KEY) that Rye has locally. Run from repo root:
 *   npx tsx scripts/process-core-assets.ts
 *   npx tsx scripts/process-core-assets.ts --dry-run   # process locally, no R2 upload
 */
import "dotenv/config";
import sharp from "sharp";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { CORE_ASSETS, type CoreAssetId } from "../client/src/pages/core/coreAssets";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const RAW_DIR = join(REPO_ROOT, "client", "public", "core", "raw");
const MANIFEST = join(REPO_ROOT, "client", "src", "pages", "core", "asset-manifest.json");
const DRY_RUN = process.argv.includes("--dry-run");

function s3(): S3Client {
  const region = process.env.AWS_REGION || "auto";
  const endpoint = process.env.AWS_ENDPOINT_URL;
  return new S3Client({
    region,
    ...(endpoint ? { endpoint } : {}),
    credentials: {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID || "",
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || "",
    },
  });
}

async function upload(client: S3Client, key: string, body: Buffer, contentType: string) {
  if (DRY_RUN) return;
  await client.send(new PutObjectCommand({ Bucket: process.env.AWS_BUCKET_NAME, Key: key, Body: body, ContentType: contentType, CacheControl: "public, max-age=31536000, immutable" }));
}

async function main() {
  if (!DRY_RUN && !process.env.AWS_BUCKET_NAME) {
    console.error("AWS_BUCKET_NAME not set. Use --dry-run to process without uploading.");
    process.exit(1);
  }
  const client = s3();
  const manifest: { _note: string; assets: Record<string, { ready: boolean; lqip: string; widths: number[] }> } = {
    _note: "Generated by scripts/process-core-assets.ts. Maps CoreAssetId -> { ready, lqip, widths }.",
    assets: {},
  };

  const ids = Object.keys(CORE_ASSETS) as CoreAssetId[];
  for (const id of ids) {
    const asset = CORE_ASSETS[id];
    const raw = join(RAW_DIR, `${id}.png`);
    if (!existsSync(raw)) {
      console.warn(`skip ${id}: raw not found (${raw})`);
      continue;
    }
    const [aw, ah] = asset.aspect;
    const isEmblem = id === "core-emblem";
    const input = readFileSync(raw);

    for (const w of asset.widths) {
      const h = Math.round((w * ah) / aw);
      const base = sharp(input).resize(w, h, { fit: "cover", position: "attention" });

      const webp = await base.clone().webp({ quality: 82 }).toBuffer();
      await upload(client, `core/${id}-${w}.webp`, webp, "image/webp");

      const avif = await base.clone().avif({ quality: 55 }).toBuffer();
      await upload(client, `core/${id}-${w}.avif`, avif, "image/avif");

      if (isEmblem) {
        const png = await base.clone().png().toBuffer();
        await upload(client, `core/${id}-${w}.png`, png, "image/png");
      }
      console.log(`${DRY_RUN ? "[dry] " : ""}${id} @ ${w}x${h}`);
    }

    // LQIP: 24px wide blurred webp as a data URI.
    const lqipBuf = await sharp(input).resize(24).blur(1).webp({ quality: 40 }).toBuffer();
    const lqip = `data:image/webp;base64,${lqipBuf.toString("base64")}`;

    manifest.assets[id] = { ready: true, lqip, widths: asset.widths };
  }

  writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2) + "\n");
  console.log(`\nWrote manifest with ${Object.keys(manifest.assets).length} ready assets -> ${MANIFEST}`);
  if (DRY_RUN) console.log("(dry-run: nothing uploaded to R2)");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
